### ISSUE TITLE
[BUG]Full rewards not being received. 0.25 only. Latest version on windows 10. How do I claim the remaining 1.75 rewards??

### ISSUE THREAD

**Issue by 1980tom** [silicoin-network/silicoin-blockchain#100]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop**

- OS: 
- OS Version/Flavor: 
- CPU: 

**Additional context**

**Comment by 1980tom** [comment]
![image](https://user-images.githubusercontent.com/84779651/137697014-ba7f0afc-854a-4071-9f06-9add0e7b2062.jpeg)

**Comment by chiamb** [comment]
I also have this problem
