### ISSUE TITLE
Wrong Estimated Time to Win

### ISSUE THREAD

**Issue by rkandel** [silicoin-network/silicoin-blockchain#105]
**Describe the bug**
The Estimated Time to Win is totally distorted. My GUI have been saying ~40 minutes to win for last 24 hours. However, there have been only 3 blocks in about 24 hours even with 32 SIT staking.

**To Reproduce**
![2021-10-27 22_03_28-Silicoin](https://user-images.githubusercontent.com/6655937/139054283-54aaba66-9af9-4b57-ae57-587b38c0e111.png)

**Comment by silahendaz** [comment]
hi. how can i my old chia plots (x58 plots)  in silicoin program ?   silicoin program not identify that plots. help pls
