### ISSUE TITLE
[BUG]the same port 9444 as spare

### ISSUE THREAD

**Issue by KobeKomi** [silicoin-network/silicoin-blockchain#11]
the same node peer port(9444) as spare-blockchain

**Comment by Brianvlaze** [comment]
Hi! have you been able to solve it? have you been able to mine both at the same time?

**Comment by SrMazas** [comment]
Go to C:\Users\(your user)\.silicoin\mainnet\config, open config.yaml with notepad. Go to edit, replace. Find 9444 (The actual port) and replace with 5444. Save, restart the gui and sync work.

**Comment by Prototype61** [comment]
I did change it but the full node is still on 9444

**Comment by albertxuzeng** [comment]
Silicoin may not work properly with other Chia fork project at the same machine. So please try to close other Chia fork project or use another machine to run Silicoin.
