### ISSUE TITLE
[BUG] only 0.125 won

### ISSUE THREAD

**Issue by stanchiam** [silicoin-network/silicoin-blockchain#111]
where is the other sit gone to? only 0.125 won

**Comment by MycaelRaustin** [comment]
I think this is a problem related to staking.
You need to stake first to earn 1SIT.
Without staking, you end up with 0.125SIT

That's just my guess though.

My experience:
I kept getting 0.125SIT
I tried staking, now I suddenly keep getting 1SIT instead.
Resolved on my side <3

**Comment by stanchiam** [comment]
> I think this is a problem related to staking. You need to stake first to earn 1SIT. Without staking, you end up with 0.125SIT
> 
> That's just my guess though.
> 
> My experience: I kept getting 0.125SIT I tried staking, now I suddenly keep getting 1SIT instead. Resolved on my side <3

no, silicoin now reward only 1 sit instead of 2 sit, and you get 1/7 if you are farming with nft plot, so u get 0.125 and the rest 7/8 goes to the pool, you can only claim it after one week
