### ISSUE TITLE
[BUG] Only 10% of Tsit on Sit wallet

### ISSUE THREAD

**Issue by feliperiosm** [silicoin-network/silicoin-blockchain#114]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop**

- OS: 
- OS Version/Flavor: 
- CPU: 

**Additional context**

**Comment by extrasolarCHIA** [comment]
yeah they said 1:1 conversion, this is fraud.

**Comment by PrEzi3** [comment]
it is what it is but it is not a bug.... 
has been communicated that the conversion ratio will finally be 10:1.

**Comment by MycaelRaustin** [comment]
Very sad over this also.
Really expected 1:1 ratio :(

**Comment by extrasolarCHIA** [comment]
> it is what it is but it is not a bug.... has been communicated that the conversion ratio will finally be 10:1.

1:1 has been communicated way before.

**Comment by PrEzi3** [comment]
> > it is what it is but it is not a bug.... has been communicated that the conversion ratio will finally be 10:1.
> 
> 1:1 has been communicated way before.

look... I am not defending the decision in any way. 
I am just saying that it should NOT be labelled as a bug since it works as advertised.... 
As advertised being called a "fraud" "missed promises" or whatever...

**Comment by extrasolarCHIA** [comment]
> > > it is what it is but it is not a bug.... has been communicated that the conversion ratio will finally be 10:1.
> > 
> > 
> > 1:1 has been communicated way before.
> 
> look... I am not defending the decision in any way. I am just saying that it should NOT be labelled as a bug since it works as advertised.... As advertised being called a "fraud" "missed promises" or whatever...

Thanks for taking the time to actually write a good and valid argument. You are right of course.

**Comment by Zelza-Sagaz** [comment]
How can I tranfer tSit to Sit???

**Comment by johnnyde94** [comment]
My tSIT has not been converted to SIT yet ether
