### ISSUE TITLE
connecting to wallet

### ISSUE THREAD

**Issue by bananawar** [silicoin-network/silicoin-blockchain#115]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop**

- OS: 
- OS Version/Flavor: 
- CPU: 

**Additional context**

**Comment by Gabbionato** [comment]
Same problem in Ubuntu.
Windows all OK, but i don't use it...

Installing procedure incorrect and when I discovered the solucion appear this other..
DEB file could make life easer...
Thank you

**Comment by bananawar** [comment]
Windows 10
![1](https://user-images.githubusercontent.com/93351103/139529124-9de4d084-3825-4c54-af08-54c8af3f1e9a.jpg)

**Comment by bananawar** [comment]
Unknown service.

**Comment by digitalfreddy** [comment]
Same in Archlinux

**Comment by Bovari** [comment]
Same, in Linux Mint

**Comment by MycaelRaustin** [comment]
Happened also to me. Managed to fix it.
It's port conflict against cactus

Just go to your config yaml in
"C:\ Users \ %username% \ .sit\mainnet\config"
Modify all ports that are already used.

Just run a simple
netstat -ano|findstr "listen"
to see which ports are currently in use

Change the ports. rerun silicoin, and you're in business ;)
