### ISSUE TITLE
How Can I My chia plots on silicoin program ? 

### ISSUE THREAD

**Issue by silahendaz** [silicoin-network/silicoin-blockchain#116]
How can I add my chia plots on silicoin program ??  silicoin program not saw chia plots. says : error ??? 

help

**Comment by silahendaz** [comment]
I was created only 1 silicoin plot. program is identify only 1 silicoin plot and harvest, but not identify chia plots. that chia plots my plots and legal chia plots. (I have only x58 chia plot)


PLS help.

**Comment by silahendaz** [comment]
sorry for flood but antyone not help me..

I have 2 more seed code in chia program. And  I added that seed codes in silicoin program.

now. I will try plotting with that old seeds. maybe after silicoin program will identify my chia plots ?  is it a good idea ??? 

pls answer ladys and gentlemans. help

**Comment by silahendaz** [comment]
anyone here ???   have an idea ?

**Comment by MycaelRaustin** [comment]
Firstly, check if you're already fully synced.
There's port conflict issue right now VS cactus-blockchain.

Either:
1.) Make sure that you're not farming also cactus
2.) Change the conflicting ports on C:\Users\%username%\.sit\mainnet\config\config.yaml

If it's all synced up and running, your problem next is on getting your plots recognized, riight?
Firstly, Make sure you aren't running hpool app, it conflicts with multi-farming.
If you must use hpool, shut it down first, then have your plots recognized before running it again.

To add plots:
1.) Go to plots module
2.) Click the 3-dots option on the upper right corner of the UI
3.) Select "Add plot directory"
4.) Add the correct directory where your plots are located
5.) Wait around 5minutes and click refresh. It should work
6.) If it doesn't, restart the UI and try again. It worked for most of us, so it should work on yours.

**Comment by silahendaz** [comment]
thanks.ı fixed that problem.  now my problem zero balance :))  I have 3 keys. must a choose 1 key and full time farming only 1 keys ?  I choosen my 3.rd key and farming now. tomorow i will check again balance.

**Comment by MycaelRaustin** [comment]
Well, don't get too comfy with your current installation.
Vote is out, they intend to restart mainnet
Be on the lookout for a new installer popping out soon ;)

**Comment by silahendaz** [comment]
farming from 2 days but not balance.   only zero.

**Comment by albertcoady** [comment]
Have you updated to the latest version?
