### ISSUE TITLE
not receive any award for 2 weeks

### ISSUE THREAD

**Issue by DartDan** [silicoin-network/silicoin-blockchain#117]
HI everyone I've been mining SILICOIN for 2 weeks and no reward received.
is that normal i am connected and synchronized it says Estimated time to win a day and yet nothing comes for 2weeks.
please help
![silicoin](https://user-images.githubusercontent.com/93547103/139905654-c3873179-9b20-4cae-b914-cc477f9922b5.PNG)
!

**Comment by silahendaz** [comment]
me to. for 3 days not reward

**Comment by nguyenhaiduong0312** [comment]
Do you use ubuntu? Can you tell me the way to install it?

**Comment by silahendaz** [comment]
using windows 10 64 bit. I added my chia plots. now I have 62 plots. program says : farming.. all plots farming..  but from 3 days "0" zero balance

**Comment by DartDan** [comment]
> 
> 
> Do you use ubuntu? Can you tell me the way to install it?

**Comment by DartDan** [comment]
> 
> 
> Do you use ubuntu? Can you tell me the way to install it?

Sorry mate can not help you with ubuntu.

**Comment by Aminacatim** [comment]
I had same issue and this worked for me:
For Windows:

1. Delete this folders:
-C:\Users\name\AppData\Roaming\silicoin
-C:\Users\name\AppData\Local\silicoin
-C:\Users\name\.sit folder

2. You also need to delete the silicoin in this location:
-Control Panel\User Accounts\Credential Manager

After first install, I generated a new key (wallet) than my master wallet with the plots, after syncing I have change to master wallet, after that the same issue. No block reward for a week. But after this steps, it worked. I had this issue with more than 5 forks from chia.

**Comment by silahendaz** [comment]
4 days and ZERO BALANCE. my all 62 plots farming but not coming any SIT.  only 0

**Comment by silahendaz** [comment]
5 DAYS AND ZERO BALANCE. whats problem ????  help ??????? where is tutorial ???  ı was get chia everyday from Hpool but silicoin not working. My all chia plots legal plot but silicoin  not giving me any reward. whats wrong ??? 
- I only mining on silicoin.  
- wallet status : Synced (56,824) 
- all plots legal
- I added my all key codes in silicoin program  
- not multiple farming
whats problem ???  what ????

**Comment by DartDan** [comment]
> 
> 
> I had same issue and this worked for me: For Windows:
> 
>     1. Open Silicoin and click on delete all keys.
> 
>     2. Delete this folders:
>        -C:\Users\name\AppData\Roaming\silicoin
>        -C:\Users\name\AppData\Local\silicoin
>        -C:\Users\name.sit folder
> 
>     3. You also need to delete the silicoin in this location:
>        -Control Panel\User Accounts\Credential Manager
> 
> 
> After that, make new installation.
> 
> After first install, I generated a new key (wallet) than my master wallet with the plots, after syncing I have change to master wallet, after that the same issue. No block reward for a week. But after this steps, it worked. I had this issue with more than 5 forks from chia.
> 
> Sometimes it takes time, It shows 4 hrs block reward, but i get no coins since a few days.

I've done all that but now have a new problem.
first i had problem creating a new wallet it was just spinning without showing me the 24 words but did a force reload and i manage to create new key.
and now the node does not synchronize it says not synced in red and its spinning endlessly.

**Comment by Aminacatim** [comment]
1. Scroll down.
2. Click on upper left corner on "Node" 
3. Scroll down to connections and click on "connect to other peers"
4. go to https://alltheblocks.net/silicoin
5. klick on nodes/ peers and pick one ip and port
6. enter the ip and port to silicon
7. if not working try another ip and port from the list

**Comment by DartDan** [comment]
it wor

> * down to connections and click on "connect to other peers"
> 
> * go to https://alltheblocks.net/silicoin
> 
> * klick on nodes/ peers and pick one ip and port
> 
> * enter the ip and port to silicon
> 
> * if not working try another ip and port from the list

It worked let see if i will start getting SIT now it tells me 21 hour.will let you know.
thank you very much for your assistance Aminacatim, you are star.
