### ISSUE TITLE
Nodes Problems and synchronization - Version 1.0.2

### ISSUE THREAD

**Issue by damianmadeira** [silicoin-network/silicoin-blockchain#119]
I have Silicoin version 1.0.2. I try add the following nodes manually but I cant solved this problem.
8.210.156.214:10444
119.29.164.26:10444
8.210.172.4:10444
13.58.18.26:10444 

Is there any other node for this version?
How do I pass the tSIC to SIC?

**Comment by anticmarco** [comment]
I also have problem with this version, I worked 2 days ago, now it is connected but it is unable to sync

**Comment by damianmadeira** [comment]
> I also have problem with this version, I worked 2 days ago, now it is connected but it is unable to sync

Same problem:
![image](https://user-images.githubusercontent.com/56444256/140238839-9b14472c-239e-43a0-96c6-ef78a5ed5477.png)

![image](https://user-images.githubusercontent.com/56444256/140238864-faef803c-71c8-41f0-87dd-ac96c02406d6.png)

**Comment by pzstarnet** [comment]
同样的问题

**Comment by bobyturk** [comment]
same problem with 1.0.2

**Comment by DartDan** [comment]
same problem with 1.0.2

**Comment by DartDan** [comment]
same problem with 1.0.2

**Comment by edouardcv** [comment]
![no sync](https://user-images.githubusercontent.com/91627707/141033240-3fd571d7-50fb-41d4-87ea-2c40b219a0b8.jpg)
el mismo problema desde que3 descargue la ultima version se ha quedado asi!

**Comment by damianmadeira** [comment]
not solucioned with 1.1.1 version
