### ISSUE TITLE
How to stake with 2 pc [Help]

### ISSUE THREAD

**Issue by jacklingbn** [silicoin-network/silicoin-blockchain#120]
I have 2 pc but my total plots wont combine same like chia, both my pc shows different stacking address .

**Comment by albertcoady** [comment]
Can you show me the screenshot in the "Stake" tab on 2 pc?

**Comment by jacklingbn** [comment]
> Can you show me the screenshot in the "Stake" tab on 2 pc?

![1](https://user-images.githubusercontent.com/84880915/141606616-543221aa-b367-4667-baf8-2503e5b61cda.png)
![2](https://user-images.githubusercontent.com/84880915/141606618-3691b711-b221-458e-986c-a6004bd76f32.png)

**Comment by albertcoady** [comment]
Well, you have two farmer keys in your plots, that means you have two staking addresses. So stake to these two addresses on either PC will be OK.
