### ISSUE TITLE
5 day and zero balance. not farm

### ISSUE THREAD

**Issue by silahendaz** [silicoin-network/silicoin-blockchain#121]
5 DAYS AND ZERO BALANCE. whats problem ???? help ??????? where is tutorial ??? ı was get chia everyday from Hpool but silicoin not working. My all chia plots legal plot but silicoin not giving me any reward. whats wrong ???

    I only mining on silicoin.
    wallet status : Synced (56,824)
    all plots legal
    I added my all key codes in silicoin program
    not multiple farming
    whats problem ??? what ????

- OS: windows 10 pro - 64 bit
- OS Version/Flavor: 
- CPU: < Intel(R) Xeon(R) CPU  E5420  @ 2.50GHz   2.49 GHz  (2 processor)
![NOT FARM](https://user-images.githubusercontent.com/71545435/140547718-2cea0be9-f62b-415c-8d0e-9d2dbea3b052.png)
![NOT FARM 2](https://user-images.githubusercontent.com/71545435/140547862-5e5c2141-d9ec-4af9-805f-7ef613faf4f0.png)

**Comment by GameOSX** [comment]
If you are going into any crypto, you should follow theirs announcement - they told that there will be mainnet restart in next days becouse of bug (https://www.sitnetwork.org/post/the-voting-result-of-restart)

**Comment by silahendaz** [comment]
when starting mr genius ??

**Comment by GameOSX** [comment]
How could I know as they didn't say that exactly 🙄
