### ISSUE TITLE
Please upload source code for 1.1.0 release

### ISSUE THREAD

**Issue by Forusim** [silicoin-network/silicoin-blockchain#122]
1. Releasing binaries without source code is not very trustworthy.
2. Without updated source code many docker containers will not be able to update to latest version.

**Comment by dipol0** [comment]
git clone https://github.com/silicoin-network/silicoin-blockchain.git

download version after sit init generate config eith old port - 11444 (not 22222). Update source please.

**Comment by drakosa13** [comment]
> git clone https://github.com/silicoin-network/silicoin-blockchain.git
> 
> download version after sit init generate config with old port - 11444 (not 22222). Update source please.

have some problem.... please fix asap.

**Comment by Enissay** [comment]
Is there any official HUB one should make his own docker image ?
