### ISSUE TITLE
missing coins in stacking

### ISSUE THREAD

**Issue by gs517** [silicoin-network/silicoin-blockchain#123]
updated from version v0.2.1 to v1.1.0
the /.sit folder was deleted before the update
, it was re-synchronized and the coin in the stake was gone!

p.s 
initially, I had 100+ coins in testnet
after launching mainnet, there were 17.3 coins left

I mined 9 coins in 12 days, sent them to stakes
, and after updating to the latest version, they disappeared. There are 17.3 original coins left!

**Comment by MycaelRaustin** [comment]
Well, here's my take on this:
1.) They've recently reported 1:100 ratio from TSIT(testnet) to SIT conversion. So 17.3 seems right.

2.) Says in their post that they're basing our SITs on the snapshot of 16800 height. So the new coins you've mined during the last few days along with those stakes are based on old mainnet that is restarted. It wouldn't reflect to the new network now. 
Reference: https://www.sitnetwork.org/post/report-what-s-going-on-with-silicoin-mainnet
![image](https://user-images.githubusercontent.com/34667491/141093564-1fba562b-cd26-4aff-ae29-0612312c4281.png)

**Comment by gs517** [comment]
> Well, here's my take on this: 1.) They've recently reported 1:100 ratio from TSIT(testnet) to SIT conversion. So 17.3 seems right.
> 
> 2.) Says in their post that they're basing our SITs on the snapshot of 16800 height. So the new coins you've mined during the last few days along with those stakes are based on old mainnet that is restarted. It wouldn't reflect to the new network now. Reference: https://www.sitnetwork.org/post/report-what-s-going-on-with-silicoin-mainnet ![image](https://user-images.githubusercontent.com/34667491/141093564-1fba562b-cd26-4aff-ae29-0612312c4281.png)

does it turn out they have 2 different blockchains ?
then why didn't the current blockchain load?

after all, those 9 coins that disappeared were already mined in the mainnet

**Comment by MycaelRaustin** [comment]
They restarted the original mainnet due to public voting.
All earnings were based from the 16800 snapshot.
So, sadly, all the coins we've farmed past the 16800 height is not covered (hence lost)

**Comment by edouardcv** [comment]
after update to 1.1.1 I've lost all my sit recovered from tesnet
