### ISSUE TITLE
[BUG] Old network mixups on Peers 

### ISSUE THREAD

**Issue by MycaelRaustin** [silicoin-network/silicoin-blockchain#124]
**Describe the bug**
I keep getting peers with height 75,000 above.
These are using the old port of 11444.
I've already deleted by .SIT directory in windows.
C:\Users\%username%\.sit
For now, I wrote a simple script to terminate all peers with ports that aren't 222222
This is my workaround solution to prevent getting stuck in "syncing" status to 75k height.

**To Reproduce**

Simply run the SIT application and wait for peers.
Sometime SIT will end up stuck in Syncing status since peers with height 75k above keep popping in.

**Expected behavior**
Syncing should be with peers following the current network height.
Those from old network should be excluded

**Screenshots**
None, already terminated the connections via script using "sit show -r %nodeid%"

**Desktop**
Windows 7

**Comment by albertcoady** [comment]
You can ban 11444 port on your machine.
