### ISSUE TITLE
[BUG]old peers

### ISSUE THREAD

**Issue by qianggefcnb** [silicoin-network/silicoin-blockchain#127]
peers list move the old peers :port 11444
and Height move 70000+

**Comment by MycaelRaustin** [comment]
I'm having the exact same problem.
My syncing is being affected by old peers also.

I'm using this simple bash script right now to keep myself synced.
You can use this in linux, or install cygwin to run it:

> #!/bin/sh
while true;
do echo "Checking Peers";
outsider=`./sit show -c|grep FULL|sed 's/  */,/g'|grep -v 22222|awk -F',' '{print $4}'|sed 's/\.*//g'`;
for node in $outsider; do ./sit show -r $node;echo terminated $node; done;
sleep 60
done;

**Comment by qianggefcnb** [comment]
Maybe a new version will fix this BUG

**Comment by MycaelRaustin** [comment]
Maybe... but atleast we have workarounds to profit from the time while waiting ;)

**Comment by qianggefcnb** [comment]
![image](https://user-images.githubusercontent.com/90693516/141107267-7105bcb9-060d-4742-83a8-3d46235c5e09.png)

**Comment by MycaelRaustin** [comment]
Ikr, gotta kill those 11444 ports
Only those with port 22222 are valid ;)

**Comment by dong3625260** [comment]
垃圾的要命，更新的新版本还是一样。

**Comment by dong3625260** [comment]
SIT昨晚更新了版本1.1.1，但新版依然串链11444的原端口，串链后就无法有效挖矿除非手动删除串进来的节点，从阴谋论角落是不是可以大胆的假设：

项目方手里有两个不同的版本分叉，一个分叉是他们自己用的，不会串链的，另一个分叉是给我们用的让我们无法摆脱串链困扰，这样项目方自己就可以多挖币了。

**Comment by MycaelRaustin** [comment]
Yes @dong3625260  - It seems that the new version1.1.1 didn't fix the problem of mixed peers.
So, either we delete the peers manually or programmatically through a script.
I simply chose the latter.

Eventually they might be able to fix this problem, but I'm not that patient of a guy to wait for a perma fix.
Haha, I'll stick with workarounds to terminate 11444 peers :P

**Comment by albertcoady** [comment]
Please try to ban port 11444  to see whether it can help.

**Comment by qianggefcnb** [comment]
The port11444 is disabled, but the problem still exists

**Comment by albertcoady** [comment]
The port 11444 will be disconnect automatically after a while。
