### ISSUE TITLE
[BUG]需要0.05版本的~修正這些問題

### ISSUE THREAD

**Issue by Nok74** [silicoin-network/silicoin-blockchain#13]
**Describe the bug**
A clear and concise description of what the bug is. (If what you are experiencing is NOT a bug but instead a support issue, please open a Discussion instead!)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Linux]
- OS Version/Flavor: [e.g. CentOS 7.2]
- CPU: [e.g. Intel Xeon 8175M]

**Additional context**
![未命名123](https://user-images.githubusercontent.com/86510052/123896942-1d4ef380-d995-11eb-8360-d1c113d0a9d0.jpg)

**Comment by Nok74** [comment]
![未命名123](https://user-images.githubusercontent.com/86510052/123896838-eaa4fb00-d994-11eb-83bd-73b53c45a8e7.jpg)

**Comment by albertxuzeng** [comment]
Please provide the OS version, silicoin version and the following files:

~/.silicoin/config/config.yaml
~/.silicoin/log/debug.log
