### ISSUE TITLE
[BUG]not synced .peaktime cycling total lterations cycling and blocks cycling.

### ISSUE THREAD

**Issue by wc357** [silicoin-network/silicoin-blockchain#132]
not synced .peaktime cycling total lterations cycling and blocks cycling.
connection status is connected.

**Comment by albertcoady** [comment]
Please try to connect to nodes below manually.

47.243.76.11:22222
82.157.30.197:22222
42.194.142.34:22222
18.135.187.74:22222
3.68.181.176:22222
18.179.135.79:22222
3.106.3.111:22222
