### ISSUE TITLE
11444-Peers are still being added to the pool causing temporary desync issues

### ISSUE THREAD

**Issue by PrEzi3** [silicoin-network/silicoin-blockchain#134]
I know it will _eventually_ fix itself once all the farmers finally noticed the switch.... but it is really annoying that from time to time an "old" 11444 full node peer will get added into the pool.

Can you please fix it?  Version 1.1.1 didn't help.

**Comment by albertcoady** [comment]
Just ban the port 11444 on your machine to see whether it can help.
