### ISSUE TITLE
[BUG] Harvester won't work with 6k plots

### ISSUE THREAD

**Issue by kiote99** [silicoin-network/silicoin-blockchain#136]
**Describe the bug**
I have two harvesters with identical configs, harv1 has 1700 plots and harv2 has 6000 plots.  Harv1 connects to the farmer just fine, Harv2 connects to the farmer but shows up with 0 plots, even after 10+ hours.

Looking in the debug log for Harv2 I found this error:
```
2021-11-13T09:09:05.479 harvester chia.rpc.rpc_server     : WARNING  Sending data failed. Exception Traceback (most recent call last):
  File "chia/rpc/rpc_server.py", line 69, in _state_changed
  File "aiohttp/client_ws.py", line 150, in send_str
  File "aiohttp/http_websocket.py", line 687, in send
  File "aiohttp/http_websocket.py", line 643, in _send_frame
  File "aiohttp/http_websocket.py", line 660, in _write
ConnectionResetError: Cannot write to closing transport
```

The only difference between the two harvesters is the number of plots.  Both are running v1.1.1, have been initialized using the farmer's certs, and are connecting to the farmer.   I am not farming Cactus.

**To Reproduce**

1. Run a harvester with 6000+ plots
2. Connect harvester to farmer

**Expected behavior**
Harvester shows up with correct number of plots.

**Screenshots**

![Screenshot from 2021-11-13 13-49-16](https://user-images.githubusercontent.com/2924945/141613515-921e07f8-031a-46a7-8ba2-838e68693a40.png)

**Desktop**

Farmer - 
- OS: Ubuntu 20.04
- CPU: Intel i7 

Harvester1 - 
- OS: Ubuntu 20.04
- CPU: Intel(R) Xeon(R) CPU E5-2690 0 @ 2.90GHz

Harvester2 - 
- OS: Ubuntu 20.04
- CPU: 2 X Intel(R) Xeon(R) CPU E5-2665 0 @ 2.40GHz

**Additional context**

**Comment by kiote99** [comment]
![Screenshot from 2021-11-13 13-49-16](https://user-images.githubusercontent.com/2924945/141613504-59da06be-44e5-4f8e-b530-733eeb6db7e7.png)

**Comment by albertcoady** [comment]
Please restart the harvester and try to load 3000 plots first, then after it show on the farmer, load the other 3000 plots.

**Comment by kiote99** [comment]
I was able to get it working with less than 3000 plots, but I'm not sure what you mean when you say "load the other 3000 plots".  I stopped the harvester, updated the config to include the other plot directories, and started the harvester with more than 3000 plots - which resulted in 0 plots showing up on the farmer again.

**Comment by kiote99** [comment]
I get inconsistent results when starting the harvester with less than 3000 plots, sometimes they appear as expected but sometimes I get a 0 in the farm summary.

**Comment by PrEzi3** [comment]
@kiote99      have 3000 plots in the pool / config, then run harvester and perform   
sit plots add -d PATH
to add more plot directories and see what happens.

**Comment by kiote99** [comment]
This kind of worked, I wrote a script to add a new directory (each containing 145 plots) every 10 minutes and let it run over night.  The farmer is reporting the harvester has ~4300 out of what should be 6000 plots.  The debug log on the harvester shows response times are now up to 1400s.

**Comment by PrEzi3** [comment]
@kiote99  Thanks for reporting the behavior back.

@albertcoady    It might be related to what I have reported right afterwards (really bad harvester performance observed on low powered devices incl. long loading times and high resource usage): 
https://github.com/silicoin-network/silicoin-blockchain/issues/137
Seems this issue is really hurting harvesting...
