### ISSUE TITLE
[BUG] No proofs found

### ISSUE THREAD

**Issue by Jaga-Telesin** [silicoin-network/silicoin-blockchain#14]
EDIT (for admins):   Finally found a proof, 5-6 hours after adding plots and starting farming/harvesting.  It may have been an anomaly that it went for so long without a hit, but you -may- want to look into it regardless.  :)

==================

**Describe the bug**
Proofs found for all challenges results in "0".  Over 5 hours monitoring with ~450 plots.  ETW is 3 hours, not one proof found in all 5 hours.

**To Reproduce**

1. Go to 'Farm tab'
3. Scroll down to 'Last attempted proof'
4. See error:  0 proofs found (3 hours with ~450 plots)

**Expected behavior**
Silicoin has a consistent "0" proofs found for all challenges.  Note:  I get an average Plots Passed Filter value (every challenge) of 15, usually between 10 and 28.

**Desktop (please complete the following information):**

- OS: Windows 10
- CPU: i7-6700K

**Additional context**
I know this server is working since both Chia and Flax connect, pass filters, and find proofs regularly.  The server has won XFX (Flax coins) in the last ~4 days.  I gave Silicoin the exact same firewall permissions/exceptions as I gave Chia/Flax (on it's ports).  Silicoin syncs the blockchain and wallet just fine, connects to plenty of peers, and completes challenges every period.

Log level is set to INFO, and I browsed it to search for "1 proofs." which came up with nothing.  Ports verified to not conflict with either Chia or Flax's installations.  External port forwarded manually, with UPNP disabled.

It seems like either the Windows Silicoin client is broken, or something about the Silicoin implementation is broken.  I should be seeing at least 1 proof in all that time, with that ETW, and with the number of plots passing filters.

**Comment by Jaga-Telesin** [comment]
Quick update:   I am also noticing the following entries in the log file:

`harvester chia.harvester.harvester:ERROR  Error using prover object Invalid size for deltas:`

Note:  the plots I am using with Silicoin right now are the same ones that work (and don't generate this error) in both Chia and Flax.   Not sure why they'd be showing up in Silicoin.

**Comment by Threadgodripper** [comment]
Same low drop rate after update 0.04
