### ISSUE TITLE
No reward for several days

### ISSUE THREAD

**Issue by anticmarco** [silicoin-network/silicoin-blockchain#140]
I am farming for several days but still no rewards, is that normal or I need to fix something? Estimated Time to Win is 10 hours

**Comment by PrEzi3** [comment]
Estimated time to win is.... well.... an estimation..... and especially after introducing staking it is completely off for me.
E.g. my estimated time to win is 2 hours, and if I am lucky I am getting 1-2 coins per day...

**Comment by albertcoady** [comment]
How many plot files do you farming and how many SIT are you staking?

**Comment by PrEzi3** [comment]
I personally am at ca 3950 plots, staking 37 SITs now. Funny enough I was able to be lucky five times yesterday. but the day earlier only solved two blocks.

**Comment by albertcoady** [comment]
You can visit https://tokendock.io/tools to get the difficulty factor you have.
