### ISSUE TITLE
upgraded to 1.1.1(Venus) lost my 2 SIT Coins.[BUG]

### ISSUE THREAD

**Issue by KaptainErk** [silicoin-network/silicoin-blockchain#141]
**Describe the bug**
Upgraded client from 1.0.2 to 1.1.1(Venus) as instructed re sink from scratch and now my 2 SIT coins are gone.

**To Reproduce**

**Expected behavior**
Do an upgrade and not loose the coin in your wallet.

**Screenshots**

**Desktop**

- OS: windows
- OS Version/Flavor: 10
- CPU: intel core i7

**Additional context**

**Comment by PrEzi3** [comment]
Not a bug - there was a restart of the full network (snapshot was taken at the height of 16800). 
Read the blog on Sitnetwork.org.
