### ISSUE TITLE
The nft does not belong to you[BUG]

### ISSUE THREAD

**Issue by chiamb** [silicoin-network/silicoin-blockchain#142]
I try to recover 1.75 sit but get this error: **the nft doesnt belong to you**
When I put my pool contact address i see my Sit but when add louncher ID I get that error. 
And also i didnt opet any block for 20 days with my estimate 8 hours and my personal difficulty is 5.1 so with calculator I must open block in two days.

**Comment by albertcoady** [comment]
Have you upgrade to 1.1.3?

**Comment by chiamb** [comment]
> 
> 
> Have you upgrade to 1.1.3?

Yes I did before that.

**Comment by albertcoady** [comment]
You need to import the same key which create the NFT in your Chia client.

**Comment by chiamb** [comment]
I import key and get message succes for missing sit. I need to wait to sync wallet. 
But why I not open blocks?
