### ISSUE TITLE
[BUG]only 0.125

### ISSUE THREAD

**Issue by qianggefcnb** [silicoin-network/silicoin-blockchain#144]
The new version has been released for more than a week. Why did I only get 0.125?

**Comment by albertcoady** [comment]
You need to claim 0.875 manually on "NFT" tab or in command line.

**Comment by qianggefcnb** [comment]
What shall I do?

**Comment by qianggefcnb** [comment]
> 您需要在“NFT”选项卡或命令行中手动声明 0.875。
When can the exchange resume trading?
