### ISSUE TITLE
Replace ports

### ISSUE THREAD

**Issue by behrendsr** [silicoin-network/silicoin-blockchain#146]
**Describe the bug**
Ports conflicting with existing forks (Cactus)

**To Reproduce**

**Expected behavior**

Init and use of SIT without conflicting ports

**Screenshots**

N/A

**Desktop**

N/A

- OS: Linux / Windows
- OS Version/Flavor: All
- CPU: N/A

**Additional context**
Replace ports in initial config file

sed -i 's/11000/22000/g' initial-config.yaml
sed -i 's/11222/22222/g' initial-config.yaml
sed -i 's/11256/22256/g' initial-config.yaml
sed -i 's/11445/22445/g' initial-config.yaml
sed -i 's/11446/22446/g' initial-config.yaml
sed -i 's/11447/22447/g' initial-config.yaml
sed -i 's/11448/22448/g' initial-config.yaml
sed -i 's/11449/22449/g' initial-config.yaml
sed -i 's/11555/22555/g' initial-config.yaml
sed -i 's/11559/22559/g' initial-config.yaml
sed -i 's/11560/22560/g' initial-config.yaml
sed -i 's/12444/22444/g' initial-config.yaml
sed -i 's/21234/22234/g' initial-config.yaml
sed -i 's/22222/22222/g' initial-config.yaml
sed -i 's/514/22514/g'   initial-config.yaml
sed -i 's/56400/22400/g' initial-config.yaml
sed -i 's/56402/22402/g' initial-config.yaml

**Comment by albertcoady** [comment]
You can change the port manually in config.yaml
