### ISSUE TITLE
status Not Synced error

### ISSUE THREAD

**Issue by silahendaz** [silicoin-network/silicoin-blockchain#149]
I have 62 chia and 1 silicoin plot. All plots legal and I m not multiple farming. I was stopped hpool farming for 3 week ago.  how can I fix this problem ? 
![silicoin1](https://user-images.githubusercontent.com/71545435/142678790-eaba7397-5b02-4719-9b16-66506b235dac.png)
,,,
![silicoin2](https://user-images.githubusercontent.com/71545435/142678827-1895127e-f27b-46ba-b805-42cc4182e5c5.png)

help pls.

**Comment by PrEzi3** [comment]
Please provide more information because now we have two printscreens which say virtually nothing.
Which version of SIT, which ports, have you followed the upgrade process to the letter, post some debug.logs etc. etc. 
There are just TOO MUCH information missing to do anything with this bug report....

**Comment by silahendaz** [comment]
-last version. 1.1.3
-I not changing ports. only I accept all attentions  when  registering.

 where is debug txt file ?cant find.

**Comment by albertcoady** [comment]
Please close the Silicoin app and delete ~/.sit folder, reopen and sync all the blocks from the beginning.

**Comment by silahendaz** [comment]
1-uninstall SIT program,
2-delete -/.sit folder.
3-install SIT program.


open SIT program and :

2021-11-21T20:19:51.427 harvester chia.plotting.manager   : WARNING  Plot H:\temporary folder location\plot-k32-2021-11-01-21-32-0370d4dbb04eef4663dc7520c6b2e196c9637199bf416968b1739dc00a0df9a6.plot **has a farmer public key that is not in the farmer's pk list.**


ı cant farm. HELP !

**Comment by albertcoady** [comment]
> 1-uninstall SIT program, 2-delete -/.sit folder. 3-install SIT program.
> 
> open SIT program and :
> 
> 2021-11-21T20:19:51.427 harvester chia.plotting.manager : WARNING Plot H:\temporary folder location\plot-k32-2021-11-01-21-32-0370d4dbb04eef4663dc7520c6b2e196c9637199bf416968b1739dc00a0df9a6.plot **has a farmer public key that is not in the farmer's pk list.**
> 
> ı cant farm. HELP !

You need to import the key that used to plot your plot files.

**Comment by silahendaz** [comment]
> > 1-uninstall SIT program, 2-delete -/.sit folder. 3-install SIT program.
> > open SIT program and :
> > 2021-11-21T20:19:51.427 harvester chia.plotting.manager : WARNING Plot H:\temporary folder location\plot-k32-2021-11-01-21-32-0370d4dbb04eef4663dc7520c6b2e196c9637199bf416968b1739dc00a0df9a6.plot **has a farmer public key that is not in the farmer's pk list.**
> > ı cant farm. HELP !
> 
> You need to import the key that used to plot your plot files.

which key ?  I import already my  keys. (24 words)   whats problem ? why cant i fix it.

**Comment by abspoel99** [comment]
1) Backup .SIT folder,
2) uninstall app,
3) delete /Username/.SIT folder, /Username/AppData/Local/SIT and... /Username/AppData/Roaming/SIT.
4) Install App,
5) Run App and whait 5 min (here was the problem as it didn't actually want to connect to any peers or introducer)
6) Close App,
7) Copy from backup: DB (only blockchain_v1_mainnet.sqlite) and Wallet (blockchain_wallet_v1_mainnet_XXXXXXXXX.sqlite)
8) Copy from backup peer_table_node.sqlite  
9) Re-stake

**Comment by albertcoady** [comment]
Can you farm now?

> > > 1-uninstall SIT program, 2-delete -/.sit folder. 3-install SIT program.
> > > open SIT program and :
> > > 2021-11-21T20:19:51.427 harvester chia.plotting.manager : WARNING Plot H:\temporary folder location\plot-k32-2021-11-01-21-32-0370d4dbb04eef4663dc7520c6b2e196c9637199bf416968b1739dc00a0df9a6.plot **has a farmer public key that is not in the farmer's pk list.**
> > > ı cant farm. HELP !
> > 
> > 
> > You need to import the key that used to plot your plot files.
> 
> which key ? I import already my keys. (24 words) whats problem ? why cant i fix it.

**Comment by silahendaz** [comment]
> Can you farm now?
> 
> > > > 1-uninstall SIT program, 2-delete -/.sit folder. 3-install SIT program.
> > > > open SIT program and :
> > > > 2021-11-21T20:19:51.427 harvester chia.plotting.manager : WARNING Plot H:\temporary folder location\plot-k32-2021-11-01-21-32-0370d4dbb04eef4663dc7520c6b2e196c9637199bf416968b1739dc00a0df9a6.plot **has a farmer public key that is not in the farmer's pk list.**
> > > > ı cant farm. HELP !
> > > 
> > > 
> > > You need to import the key that used to plot your plot files.
> > 
> > 
> > which key ? I import already my keys. (24 words) whats problem ? why cant i fix it.

**yes now SYNCHED and my 62 plots FARMİNG but not coming any SIT ???  how can I gain Silicoin ?**


![silicoin3](https://user-images.githubusercontent.com/71545435/143074790-332ad02b-3921-41ab-b22c-541881667cb6.png)

![silicoin4](https://user-images.githubusercontent.com/71545435/143074821-02d9189d-8819-4665-9010-fe2395b9b3ea.png)
![silicoin5](https://user-images.githubusercontent.com/71545435/143074836-831c4e75-b537-41fc-b93e-c8ef27ee31e6.png)

**Comment by albertcoady** [comment]
How many SIT are you staking?
