### ISSUE TITLE
Remote Harvester not able to connect to Farmer

### ISSUE THREAD

**Issue by maxchock** [silicoin-network/silicoin-blockchain#150]
Hi, I have a harvester at home, and a remote farmer at my office. before update to 1.1.3, everything works fine. after upgrade, harvester unable to connect to remote farmer.

here is the result for command : **./sit farm summary**
Farming status: Not synced or not connected to peers
Total silicoin farmed: 0.0
User transaction fees: 0.0
Block rewards: 0.0
Last height farmed: 0
Local Harvester
   1590 plots of size: 157.373 TiB
Plot count for all harvesters: 1590
Total size of plots: 157.373 TiB
Staking addresses:
  sit1xcutv4a54wcx454a8v8xqpf4akklvecp293k0xmfzhahp99dt6rqrxnvfn (balance: 0, plots: 1590)
Estimated network space: 885.276 TiB
Expected time to win: 1 minute
Note: log into your key using 'sit wallet show' to see rewards for each key

other Chia fork works just fine, for example **hddcoin**:

Farming status: Farming
Total hddcoin farmed: 278.5
User transaction fees: 0.0
Block rewards: 278.5
Last height farmed: 637686
Harvester 113.211.208.115:41968:
   195 plots of size: 19.300 TiB
Harvester 127.0.0.1:53018:
   1590 plots of size: 157.373 TiB
Plot count for all harvesters: 1785
Total size of plots: 176.672 TiB
Estimated network space: 1.877 EiB
Expected time to win: 2 days and 13 hours
Note: log into your key using 'hddcoin wallet show' to see rewards for each key
Done

**Comment by albertcoady** [comment]
Is there any log about this connection problem on both farmer machine and harvester machine?
