### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by blitz55555** [silicoin-network/silicoin-blockchain#153]
When attempting to withdraw SIT that has been staked, I get the following error when clicking "withdraw" - "No key for this puzzlehash", followed by the puzzlehash. In essence, I am able to stake SIT, but cannot withdraw it due to this error. I have two different types of Plots, NFT and Original (solo) plots. The issue appears to only happen with the Original (solo) plots.

**Comment by albertcoady** [comment]
Did you farm NFT and Original plots in the same farmer machine?

**Comment by blitz55555** [comment]
I did not, they were farmed with a couple of different machines, but all using the same keys.

**Comment by albertcoady** [comment]
You need to log in using the correct key from staking address before you withdraw if you have multiple keys.
