### ISSUE TITLE
Staking coin all missing after updated to 1.1.3.

### ISSUE THREAD

**Issue by maxchock** [silicoin-network/silicoin-blockchain#154]
Was staking every reward I got while using 1.0.x version, therefore, the staking wallet supposed to have around 300 to 400 SIT. staking wallet address: sit1xcutv4a54wcx454a8v8xqpf4akklvecp293k0xmfzhahp99dt6rqrxnvfn

But after updated to 1.1.3, below result show after I execute
**./sit farm summary**

Farming status: Farming
Total silicoin farmed: 0.0
User transaction fees: 0.0
Block rewards: 0.0
Last height farmed: 0
Local Harvester
   1590 plots of size: 157.373 TiB
Remote Harvester for IP: 113.211.208.115
   195 plots of size: 19.300 TiB
Plot count for all harvesters: 1785
Total size of plots: 176.672 TiB
Staking addresses:
  sit1xcutv4a54wcx454a8v8xqpf4akklvecp293k0xmfzhahp99dt6rqrxnvfn (balance: 0, plots: 1785)
Estimated network space: 177.441 PiB
Expected time to win: 5 hours and 48 minutes
Note: log into your key using 'sit wallet show' to see rewards for each key

The balance of my staking address is 0?? and why total silicoin farmed is 0.0??? it was at least like 300 ~ 400

**Comment by albertcoady** [comment]
The mainnet had restarted for version 1.1.x.

**Comment by maxchock** [comment]
> The mainnet had restarted for version 1.1.x.

Thanks for the reply. Will I get back my staking coin then?
