### ISSUE TITLE
[BUG] Centos7.3  notInternet, how to install SIT

### ISSUE THREAD

**Issue by JustAlias** [silicoin-network/silicoin-blockchain#155]
My Chia harvester does not have Internet, it is Centos7.3, it can run Chia harvester  normally ,how should I compile the source code to install SIT? Are there detailed instructions?

**Comment by JustAlias** [comment]
I have 3P chia plots  ,It's  easy to Run，But SIT will not be installed，it't too hard

**Comment by albertcoady** [comment]
How did you run Chia without Internet on your harvester?

**Comment by JustAlias** [comment]
> 

The harvester is on the LAN, connected to Farmer's server，Farmer in a dual network

**Comment by albertcoady** [comment]
1. Clone the source code tag 1.1.3 from Github on your farmer machine.
2. Run "sh install.sh" command
3. Copy the "Silicoin-blockchain" folder to your harvester

**Comment by JustAlias** [comment]
> 1. 在您的农民机器上从 Github 克隆源代码标记 1.1.3。
> 2. 运行“sh install.sh”命令
> 3. 将“Silicoin-blockchain”文件夹复制到你的收割机



Thank you very much for your reply. I'll try it tomorrow

**Comment by JustAlias** [comment]
Install. Sh failed to run on centos7, it is beyond my capacity, request official centos7 compatibility
Others forks and chia farming well，They are all the same and simple to install. 
Perhaps the difficulty of installation is why SIT is not as popular
thaks!

**Comment by JustAlias** [comment]
> 1. Clone the source code tag 1.1.3 from Github on your farmer machine.
> 2. Run "sh install.sh" command
> 3. Copy the "Silicoin-blockchain" folder to your harvester

Install. Sh failed to run on centos7, it is beyond my capacity, request official centos7 compatibility
Others forks and chia farming well，They are all the same and simple to install.
Perhaps the difficulty of installation is why SIT is not as popular
thaks!
