### ISSUE TITLE
only 1 sit coin for block reward[BUG]

### ISSUE THREAD

**Issue by KaptainErk** [silicoin-network/silicoin-blockchain#157]
**Describe the bug**
only 1 sit coin for block reward height 75885. 0.125 and 0.875

Incoming | sit1vdz568u893fafcus3ttr552u4z3mz6qjgwwfm4cz5hjrgl3s65zsgt99pw | 11/21/2021 12:20:34 PM | Confirmed at height 75887 | 0.125 | 0
-- | -- | -- | -- | -- | --
Incoming | sit1vdz568u893fafcus3ttr552u4z3mz6qjgwwfm4cz5hjrgl3s65zsgt99pw | 11/21/2021 12:20:34 PM | Confirmed at height 75887 | 0.875 | 0

1. win a block
2 receive only 1 sit coin
 
**Expected behavior**
reward is 2 sit or am I incorrect

**Screenshots**

**Desktop**

- OS: windows
- OS 10
- CPU: intel i7
**Additional context**

**Comment by PrEzi3** [comment]
Not a bug. The reward is 1 SIT per block.
