### ISSUE TITLE
[BUG] duplicate ports with FLAX, besides cactus

### ISSUE THREAD

**Issue by alarik1** [silicoin-network/silicoin-blockchain#158]
Scanned sit             - Conflicts Found!
                                       State    Local Address:Port        Process
sit port 11555 in use by:              LISTEN   127.0.0.1:11555           "cactus_full_nod"
sit port 11447 in use by:              LISTEN   0.0.0.0:11447             "cactus_farmer"
sit port 11447 in use by:              ESTAB    192.168.1.199:11447       "cactus_farmer"
sit port 11447 in use by:              ESTAB    192.168.1.199:11447       "cactus_farmer"
sit port 11447 in use by:              ESTAB    127.0.0.1:11447           "cactus_farmer"
sit port 11447 in use by:              ESTAB    192.168.1.199:11447       "cactus_farmer"
sit port 11447 in use by:              ESTAB    192.168.1.199:11447       "cactus_farmer"
sit port 11447 in use by:              ESTAB    192.168.1.199:11447       "cactus_farmer"
sit port 11447 in use by:              ESTAB    192.168.1.199:11447       "cactus_farmer"
sit port 11447 in use by:              LISTEN   [::]:11447                "cactus_farmer"
sit port 11447 in use by:              ESTAB    127.0.0.1:11447           "cactus_harveste"
sit port 11559 in use by:              LISTEN   127.0.0.1:11559           "cactus_farmer"
sit port 11560 in use by:              LISTEN   127.0.0.1:11560           "cactus_harveste"
sit port 56400 in use by:              ESTAB    127.0.0.1:56400           "flax_wallet"
sit port 56400 in use by:              ESTAB    127.0.0.1:56400           "flax_daemon"

**Comment by PrEzi3** [comment]
Check again if you are using the correct FLAX config.  I am on 0.1.5 and it is 56600 and not 56400 on FLAX, thus no conflict.
So IMHO not a bug. And cactus is irrelevant anyway...

**Comment by abspoel99** [comment]
i would have to disagree with you. changing the ports is irrelevant. 

most people that are farming cactus are running 20+ forks on there systems, it is well known that these two conflict by now.
It would also be in silicoins best interest to get those farmers over to the network to increase the demand for SIT.

**Comment by PrEzi3** [comment]
Changing the ports if conflicting with relevant fork - yes. That is why I have checked quickly for the mentioned conflict with FLAX, which it's not conflicting with.

Cactus (IMHO of course) - isn't. No Netspace growth since over a month now, no value whatsoever. Dead fork to me. Prove me wrong pls.

**Comment by alarik1** [comment]
> Check again if you are using the correct FLAX config. I am on 0.1.5 and it is 56600 and not 56400 on FLAX, thus no conflict. So IMHO not a bug. And cactus is irrelevant anyway...

(venv) farmer0@farmer0:/bin/chia-forks/flax-blockchain$ flax version
0.1.5

**Comment by alarik1** [comment]
> Check again if you are using the correct FLAX config. I am on 0.1.5 and it is 56600 and not 56400 on FLAX, thus no conflict. So IMHO not a bug. And cactus is irrelevant anyway...

Also I have double-checked now in SIT and in FLAX config files, both run daemon_port: 56600
I am using original configs.

Also its not what and which is relevant/irelevant, it is a matter of appreciating another man's work and changing the damn ports when you put them on somebody elses.

I find it ridiculous to say 'cactus' is irrelevant and I find it astonishing for somebody to say that they can make misstakes and its not their obligation to change the misstakes. Others which have done nothing wrong are supposed to change these misstakes ?
Is this the kind of attitudine SIT is offering ?
WHY is this closed ????

**Comment by PrEzi3** [comment]
ubuntu@xxxxx:~/.flax/mainnet/config$ cat config.yaml |grep daemon_port
daemon_port: 56600
  daemon_port: 56600

Nuff said.

**Comment by alarik1** [comment]
I think ur only reading the lines u wanna rea, I pasted you everything in my first post.
(venv) farmer0@farmer0:/bin/chia-forks/flax-blockchain$ sudo netstat -anpe | grep "56400"
tcp        0      0 127.0.0.1:56600         127.0.0.1:56400         ESTABLISHED 1000       81162      12507/flax_daemon
tcp        0      0 127.0.0.1:56400         127.0.0.1:56600         ESTABLISHED 1000       84084      12516/flax_wallet
SIT daemon_port: 56400
Anyway, i`ll spend a few minutes re-writing SIT config ports if its too complicated for the developers. post closed :)))))
Indeed 'nuff said'

**Comment by PrEzi3** [comment]
lol. look at the initial config from flax then. There are NO 56400 ports there !  Netstat tells the same btw...
The PROBLEM in your case sits 40cm away from YOUR the PC.

**Comment by alarik1** [comment]
As I said I have original flax config, but I also had the decency to check daemon_port : 56600 in flax, yes, i understand what you`re telling me. ur just not understanding what I`m telling you.
(venv) farmer0@farmer0:/bin/chia-forks/flax-blockchain$ sudo netstat -anpe | grep "56400"
tcp 0 0 127.0.0.1:56600 127.0.0.1:**56400** ESTABLISHED 1000 81162 12507/**flax_daemon**
tcp 0 0 127.0.0.1:**56400** 127.0.0.1:56600 ESTABLISHED 1000 84084 12516/**flax_wallet**
So is it a flax issue maybe I take it up with them.
anyway nevermind I changed the config already and it connected.
