### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by edumh21** [silicoin-network/silicoin-blockchain#162]
Ask for support does not work so I will writte it in here.

I made this morning a trasaction from my Silicoin.exe to my SIT wallet on CITEX but the amount of 75 SIT sent did not arrived already. Someone knows why or if this is normal? Thanks. Here is a picture of the transaction apparently done:

![image](https://user-images.githubusercontent.com/84201557/143621988-7ec231d9-680e-48d1-84ee-60425c121048.png)

Thanks

**Comment by abspoel99** [comment]
Suggest to read this article in the FAQ from the discord channel: might be because you are running a older SIT version also try to look up the transaction. Link to the sit explorer is included in the article https://discord.com/channels/855895952757620757/864525972131545148/913881982428147722

**Comment by edumh21** [comment]
So I lost those SIT or there is any way to get them back?
