### ISSUE TITLE
[BUG]Not Synced Status

### ISSUE THREAD

**Issue by bralaiva1337** [silicoin-network/silicoin-blockchain#163]
Hello everybody,

After update silicoin-network to SIT 1.1.3(Venus)
![image](https://user-images.githubusercontent.com/91378653/143678758-4b0280fb-8ee9-4614-8e88-c49cf67ad2cf.png)
I got not synced status. I was farming SIT already from huge release and everything was fine until I download last package.
When I check log I always see error code: WARNING  querying DNS introducer failed: The DNS operation timed out after 31.621434926986694 seconds
Where I can find information which ports Silicon Network using for ? 
Have this issue already a couple days. 
Exploring a lot in Internet and didn't find nothing about it.
Others forks and chia farming well. 
Maybe someone have same issue. Really needs help.

**Comment by PrEzi3** [comment]
if you go into config.yaml you will see that the port changed to 22222.
Here are a few peers to help you sync.
120.232.166.194:22222
14.37.53.32:22222
188.108.17.127:22222
188.134.88.248:22222
95.22.80.176:22222

**Comment by bralaiva1337** [comment]
> 
Hey there!

I look up my config and find other ports on it nothing about 22222, trying also all this peers. didn't work out :(
Still confuse what's happen. 
Thank you for your help!

**Comment by PrEzi3** [comment]
If you don't see the port 22222 in the config.yaml then it seems you have not followed the upgrade process properly earlier. It clearly stated :  "please delete ~/.sit before you install this new version."

**Comment by bralaiva1337** [comment]
> If you don't see the port 22222 in the config.yaml then it seems you have not followed the upgrade process properly earlier. It clearly stated : "please delete ~/.sit before you install this new version."

Seems like everything starts work, thanks you a lot!
