### ISSUE TITLE
Don‘t farming & read NFT plots is slowly[BUG]

### ISSUE THREAD

**Issue by minguohua** [silicoin-network/silicoin-blockchain#164]
**Describe the bug**
2021-11-30T08:29:53.574 farmer chia.farmer.farmer         : WARNING  Respond plots came too late
2021-11-30T08:29:53.587 farmer chia.farmer.farmer         : ERROR    Harvester did not respond. You might need to update harvester to the latest version
2021-11-30T08:30:05.075 full_node full_node_server        : WARNING  Cannot write to closing transport 78.84.55.18
2021-11-30T08:35:54.059 harvester harvester_server        : ERROR    Exception:  <class 'asyncio.exceptions.TimeoutError'>, closing connection {'host': '127.0.0.1', 'port': 11447}. Traceback (most recent call last):
  File "chia\server\server.py", line 569, in api_call
  File "asyncio\tasks.py", line 496, in wait_for asyncio.exceptions.TimeoutError

**To Reproduce**

**Expected behavior**

**Screenshots**
<html>
<body>
<div class="MuiBox-root jss8413 Card__StyledCardTitle-sc-177c3m4-0 ewVAMm" style="box-sizing: inherit; padding: 16px; color: rgba(0, 0, 0, 0.87); font-family: Roboto; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: 0.14994px; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="MuiBox-root jss8414 Flex__StyledGapBox-sc-tj3ggw-0 hLZjOh" style="box-sizing: inherit; display: flex; flex-wrap: wrap; align-items: center;"><div class="MuiBox-root jss8415" style="box-sizing: inherit; flex-grow: 1;"><h5 class="MuiTypography-root MuiTypography-h5" style="box-sizing: inherit; margin: 0px; font-size: 1.5rem; font-family: Roboto, Helvetica, Arial, sans-serif; font-weight: 400; line-height: 1.334; letter-spacing: 0em;"><div class="MuiBox-root jss8416 Flex__StyledGapBox-sc-tj3ggw-0 cJgCii" style="box-sizing: inherit; display: flex; align-items: center;"><div class="MuiBox-root jss8417" style="box-sizing: inherit; margin-right: 8px;">Last Attempted Proof</div><svg class="MuiSvgIcon-root TooltipIcon__StyledHelpIcon-sc-ajen8y-0 lmeGei MuiSvgIcon-colorDisabled" focusable="false" viewBox="0 0 24 24" aria-hidden="true"><path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm1 17h-2v-2h2v2zm2.07-7.75l-.9.92C13.45 12.9 13 13.5 13 15h-2v-.5c0-1.1.45-2.1 1.17-2.83l1.24-1.26c.37-.36.59-.86.59-1.41 0-1.1-.9-2-2-2s-2 .9-2 2H8c0-2.21 1.79-4 4-4s4 1.79 4 4c0 .88-.36 1.68-.93 2.25z"></path></svg></div></h5></div></div></div><div class="MuiCardContent-root" style="box-sizing: inherit; padding: 16px 16px 24px; color: rgba(0, 0, 0, 0.87); font-family: Roboto; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: 0.14994px; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="MuiBox-root jss8418 Flex__StyledGapBox-sc-tj3ggw-0 fwMTor" style="box-sizing: inherit; display: flex; flex-direction: column;"><div class="MuiBox-root jss8419 Flex__StyledGapBox-sc-tj3ggw-0 iJUfUW" style="box-sizing: inherit; display: flex; flex-direction: column;"><div class="MuiPaper-root MuiTableContainer-root MuiPaper-elevation1 MuiPaper-rounded" style="box-sizing: inherit; color: rgba(0, 0, 0, 0.87); transition: box-shadow 300ms cubic-bezier(0.4, 0, 0.2, 1) 0ms; background-color: rgb(255, 255, 255); border-radius: 4px; box-shadow: rgba(0, 0, 0, 0.2) 0px 2px 1px -1px, rgba(0, 0, 0, 0.14) 0px 1px 1px 0px, rgba(0, 0, 0, 0.12) 0px 1px 3px 0px; width: 991.111px; overflow-x: auto;">

Challenge | Plots Passed Filter | Proofs Found | Date
-- | -- | -- | --
0x46cd2d0b92f504ed41c4ae9c7d221416787368950422affe159440ec1b313878 | 9 / 4412 | 0 | Nov 30, 8:06:55 AM
0x46cd2d0b92f504ed41c4ae9c7d221416787368950422affe159440ec1b313878 | 6 / 4412 | 0 | Nov 30, 8:06:55 AM
0x46cd2d0b92f504ed41c4ae9c7d221416787368950422affe159440ec1b313878 | 9 / 4412 | 0 | Nov 30, 8:06:55 AM
0x46cd2d0b92f504ed41c4ae9c7d221416787368950422affe159440ec1b313878 | 6 / 4412 | 0 | Nov 30, 8:06:55 AM
0x46cd2d0b92f504ed41c4ae9c7d221416787368950422affe159440ec1b313878 | 9 / 4412 | 0 | Nov 30, 8:06:55 AM

</div></div></div></div>
</body>
</html>
Computer time is 8:35 AM
**Desktop**

- OS: windows
- OS Version/Flavor: Server 2012R2
- CPU:E5 2696v2 64GB RAM

**Additional context**

**Comment by albertcoady** [comment]
It seems that your harvester is not working, please restart the app.

**Comment by minguohua** [comment]
restart,then can't read nft plots,must reload directory.then nothing changes.

**Comment by albertcoady** [comment]
It still show the error log like this? "2021-11-30T08:29:53.587 farmer chia.farmer.farmer : ERROR Harvester did not respond. You might need to update harvester to the latest version"

**Comment by minguohua** [comment]
YES!
When the plots over about 300TiB(3000 plots),APP harvester becomes slowly update.
CHIA harveste 1.421PiB plots but no problem.other forks is normal too.

**Comment by albertcoady** [comment]
How many forks are you farming at the same time?

**Comment by minguohua** [comment]
4 forks usally,most of 10 forks is NOT this problem. Single SIT is like this,

**Comment by albertcoady** [comment]
It is better to load around 300T plot files one time for the harvester.

**Comment by PrEzi3** [comment]
@albertcoady This is the same and related to harvester performance problems reported by me.

**Comment by PrEzi3** [comment]
Bumping up, related to #175
