### ISSUE TITLE
[BUG]The money from the account was lost

### ISSUE THREAD

**Issue by mcsham** [silicoin-network/silicoin-blockchain#166]
**Describe the bug**
I have version 1.1.2 installed. Node has stopped syncing. I upgraded to version 1.1.3, removed ./sit and fully synced. And my wallet dropped. There is no money on the balance, the staking is similar. And there were 200 coins. What could be the problem?
The recovery phrase is correct. Farming began again. Remote harvesters are not seen on old keys.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop**

- OS: Linux 20.04
- CPU: Intel Xeon 8175M 

**Additional context**

**Comment by albertcoady** [comment]
Is your wallet fully synced?

**Comment by mcsham** [comment]
> Is your wallet fully synced?

yes.

**Comment by albertcoady** [comment]
You can run command "sit farm summary" on your farmer to check your staking balance.

**Comment by mcsham** [comment]
![image](https://user-images.githubusercontent.com/40900923/144437795-ecc1a991-85c5-48e3-8399-989e6da20b61.png)

![image](https://user-images.githubusercontent.com/40900923/144438906-b3aa0dba-801a-429f-a3fd-d58effb29c1c.png)
![image](https://user-images.githubusercontent.com/40900923/144438984-e776944e-a08e-4702-942a-75b14406ce8c.png)

these 0.125 earned yesterday. stacks of accounts coincide with the old ones. And whether the account coincides with the old one, I don't know, I didn't write it down, it's my fault.
I restored the main machine with the keys I had on the combines, and the main machine saw all the combines. But there are no coins, there are none.

**Comment by albertcoady** [comment]
It seems that you upgrade from version 1.0.2 not 1.1.2. The mainnet has been restarted since 1.1.0.

https://www.sitnetwork.org/post/the-voting-result-of-restart

**Comment by albertcoady** [comment]
If you upgrade from 1.1.2 and you staked coins into your staking address, it won't disappear because the balance was recorded on the blockchain even if you delete your .sit folder.

Or maybe you have different plot files. The staking address is derived from the farmer public key which stored in your plot file.

**Comment by mcsham** [comment]
I have no other files. As you can see from the screen, all the flesh tightened up, I have no other 13k plots)) But for some reason there is no previous account. Well, we'll have to mine them again. Although I understand what you are talking about, everything had to be on the blockchain.
Now I decided to delete the entire folder and re-synchronize, it should pull up everything in the blockchain. By the way, there were no attacks on the network? 51% or something else?

**Comment by albertcoady** [comment]
There were no attacks on the network.

**Comment by mcsham** [comment]
then such a question / idea in chia is it possible to create several wallets ... perhaps another wallet was accidentally created and there are 0 coins in it, is it possible?
