### ISSUE TITLE
200TB of Plots and 7 hours time to win but no win in 2 days

### ISSUE THREAD

**Issue by Einheit-101** [silicoin-network/silicoin-blockchain#173]
Log gets spammed with these messages:

2021-12-12T04:38:13.311 full_node full_node_server        : WARNING  Peer surpassed rate limit 127.0.0.1, message: request_stakings, port 63031 but not disconnecting
2021-12-12T04:38:13.335 wallet wallet_server              : WARNING  Peer surpassed rate limit 127.0.0.1, message: respond_stakings, port 22222 but not disconnecting

2021-12-12T04:44:28.141 wallet chia.wallet.wallet_node    : ERROR    Loop exception in sync Was not able to add blocks 165848-165880. Traceback (most recent call last):
  File "chia\wallet\wallet_node.py", line 641, in sync_job
  File "chia\wallet\wallet_node.py", line 701, in _sync
  File "chia\wallet\wallet_node.py", line 598, in batch_sync_to_peak
RuntimeError: Was not able to add blocks 165848-165880

2021-12-12T04:44:28.155 wallet chia.wallet.wallet_node    : WARNING  bad peak response from peer None

probably this is a configuration issue?
i am using 1.1.3, i just updated a few hours ago to 1.1.5.

**Comment by albertcoady** [comment]
How many SIT have you staked?

**Comment by Einheit-101** [comment]
Uhm none, as i could not find further info about that yet

**Comment by MycaelRaustin** [comment]
Hey there @albertcoady :

Staking tutorial is on this project's intro readme.

See image below - Super easy with cmd on windows or command-line in linux:
![image](https://user-images.githubusercontent.com/34667491/146013442-7e0b10d8-ab4b-4334-b67a-bc376f95e7d4.png)

**Comment by albertcoady** [comment]
> Uhm none, as i could not find further info about that yet

If you are using GUI, go to the "Stake" tab. It will take some time to load plot files and select your plot farmer public key then stake SIT.

If your are using Linux, follow the https://github.com/silicoin-network/silicoin-blockchain/wiki/How-To-Stake

**Comment by atomsymbol** [comment]
> Uhm none

If staking 0 SIT then the staking factor is 20.

**Comment by Einheit-101** [comment]
> > Uhm none, as i could not find further info about that yet
> 
> If you are using GUI, go to the "Stake" tab. It will take some time to load plot files and select your plot farmer public key then stake SIT.
> 
> If your are using Linux, follow the https://github.com/silicoin-network/silicoin-blockchain/wiki/How-To-Stake

I do now stake with CLI, because in Staking Tab there is no staking address and i cant stake there... Looks like this is not actually a bug but the fact that you need to stake in order to win at all.

**Comment by albertcoady** [comment]
> > > Uhm none, as i could not find further info about that yet
> > 
> > 
> > If you are using GUI, go to the "Stake" tab. It will take some time to load plot files and select your plot farmer public key then stake SIT.
> > If your are using Linux, follow the https://github.com/silicoin-network/silicoin-blockchain/wiki/How-To-Stake
> 
> I do now stake with CLI. Looks like this is not actually a bug but the fact that you need to stake in order to win at all. Also the staking address in "Stake" UI Tab is wrong.

Yes, the "Stake" UI tab shows your farmer public key. The staking address is derived from the farmer public key.
