### ISSUE TITLE
[BUG]mainnet stop in 194887

### ISSUE THREAD

**Issue by qianggefcnb** [silicoin-network/silicoin-blockchain#177]
mainnet stop in 194887
?
What happened?

**Comment by jfikar** [comment]
I'm at 195244, but it is slow, out of sync since yesterday noon. I think it is caused by:

```
ValueError: Error short batch syncing, failed to validate block 195264
```

Are there some malicious nodes trying to DDoS the Silicoin chain?

**Comment by targin** [comment]
Have same issue despite updating to the 1.1.15 fix
Also Win10
Mine is stuck at 198,XXX
