### ISSUE TITLE
[BUG] Wallet not Syncing

### ISSUE THREAD

**Issue by Mariusp91** [silicoin-network/silicoin-blockchain#178]
The wallet does not syncing. 
The status and the connection status are both synced, but the Wallet Status: Syncing (185,628) .
I try to add rule on the router port forwarding but it doesn't change nothing.

What shoulde i do ?
Thanks

- OS: Windows
- OS Version/Flavor: <10 -->

**Comment by chrisezmr** [comment]
have the same problem since version 1.1.3

**Comment by targin** [comment]
Have same issue despite updating to the 1.1.15 fix
Also Win10
Mine is stuck at 198,XXX

**Comment by albertcoady** [comment]
Please update to version 1.1.5 and wait for some time.

**Comment by targin** [comment]
> Please update to version 1.1.5 and wait for some time.
I have and still hasn't moved for days....

**Comment by PrEzi3** [comment]
> > Please update to version 1.1.5 and wait for some time.
> > I have and still hasn't moved for days....

Have you followed the update procedures correctly ? Which ports is the fork running, mainly node ? It should connect to full nodes on port 22222 and also in the config it should be port 22222 instead of 11444 -- please check this.

**Comment by chrisezmr** [comment]
i have 1.1.5 on windows 10
it stoped at 173.556
can you send a screenshot of your config please, that we write the same in ours.

**Comment by PrEzi3** [comment]
> i have 1.1.5 on windows 10 it stoped at 173.556 can you send a screenshot of your config please, that we write the same in ours.

Do a search for 22222 in the config. If you find it means you have followed the upgrade procedure for the switch from earlier SIT to 1.1.0+.  If not -- follow the upgrade process described in the 1.1.0 and later releases.
https://github.com/silicoin-network/silicoin-blockchain/releases/tag/v1.1.0

**Comment by chrisezmr** [comment]
ok thank you, now it is syncing from 0.... will see tomorrow the result.

**Comment by xludodx** [comment]
Same problem here, fresh install from scratch, 3 days to be stuck at 195 244:

Nodes, nothing abocve 195244...
0xeb04639fbbdd8b68d54aebd59c3dc2c522273ec075ace5cf34aa3a78b6e388c0
206.172.202.249
22222/22222
0/0
Full Node
195 244
0x5f21221ee7a2d10ff40d496d7122285883cef1bdcc2c45dd096126069f51fc6f
[2001:fb1:14a:77ed:9cc5:b480:fba:e69f]
22222/22222
0/0,2
Full Node
149 207
0x261ab87508584ffe30dd383df1e6cac8d6594ecb155eba83766212f719f77a4a
81.23.63.28
22222/22222
0/0
Full Node
195 244
0x0a1243aec94b9d3cb43290691f63794eb6aebde99bb7b95f83ec0ee21c08a3fe
[2408:8226:df13:a22a:1461::795]
22222/22222
0/0
Full Node
107 003


Please help !

**Comment by PrEzi3** [comment]
@xludodx   
1. If restarting SIT doesn't help --- 
2. check if you are on 1.1.5. If no - upgrade to 1.1.5.  
3. Then do a backup of your wallet db and remove the db and let it sync from beginning.

**Comment by xludodx** [comment]
Fresh install with:
![image](https://user-images.githubusercontent.com/39327332/146916173-dab43f27-031d-406d-9b6a-a602381e9b24.png)

Nothing better.
I'll try to remove the wallet, but the chain itself is not syncing fully...

I see intermittent node with full chain but:
2021-12-21T11:39:58.449 full_node full_node_server        : ERROR    Exception: Error short batch syncing, failed to validate block 195264 <class 'ValueError'>, closing connection {'host': '2a02:8071:3e82:6d00:1ac0:4dff:fe95:c73', 'port': 22222}. Traceback (most recent call last):
  File "chia\server\server.py", line 569, in api_call
  File "asyncio\tasks.py", line 442, in wait_for
  File "chia\server\server.py", line 566, in wrapped_coroutine
  File "chia\server\server.py", line 559, in wrapped_coroutine
  File "chia\full_node\full_node_api.py", line 115, in new_peak
  File "chia\full_node\full_node.py", line 433, in new_peak
  File "chia\full_node\full_node.py", line 294, in short_sync_batch
ValueError: Error short batch syncing, failed to validate block 195264

2021-12-21T11:39:58.492 full_node full_node_server        : WARNING  Banning [2a02:8071:3e82:6d00:1ac0:4dff:fe95:c73] for 10 seconds

**Comment by LordRayden2020** [comment]
Same here...
Stuck on 195,106 for 5 days.
Fresh install with1.1.5 (I thought maybe something is wrong in the config so I deleted everything and started from scratch).
Downloaded a new DB file which is also stuck on 195,106...

**Comment by albertcoady** [comment]
> Fresh install with: ![image](https://user-images.githubusercontent.com/39327332/146916173-dab43f27-031d-406d-9b6a-a602381e9b24.png)
> 
> Nothing better. I'll try to remove the wallet, but the chain itself is not syncing fully...
> 
> I see intermittent node with full chain but: 2021-12-21T11:39:58.449 full_node full_node_server : ERROR Exception: Error short batch syncing, failed to validate block 195264 <class 'ValueError'>, closing connection {'host': '2a02:8071:3e82:6d00:1ac0:4dff:fe95:c73', 'port': 22222}. Traceback (most recent call last): File "chia\server\server.py", line 569, in api_call File "asyncio\tasks.py", line 442, in wait_for File "chia\server\server.py", line 566, in wrapped_coroutine File "chia\server\server.py", line 559, in wrapped_coroutine File "chia\full_node\full_node_api.py", line 115, in new_peak File "chia\full_node\full_node.py", line 433, in new_peak File "chia\full_node\full_node.py", line 294, in short_sync_batch ValueError: Error short batch syncing, failed to validate block 195264
> 
> 2021-12-21T11:39:58.492 full_node full_node_server : WARNING Banning [2a02:8071:3e82:6d00:1ac0:4dff:fe95:c73] for 10 seconds

What is your OS platform?

**Comment by albertcoady** [comment]
> Same here...
> Stuck on 195,106 for 5 days.
> Fresh install with1.1.5 (I thought maybe something is wrong in the config so I deleted everything and started from scratch).
> Downloaded a new DB file which is also stuck on 195,106...

Please tell me your OS platform.
