### ISSUE TITLE
[BUG]0.04 Version 0.04, the hard disk has been read non-stop, never stopped

### ISSUE THREAD

**Issue by Nok74** [silicoin-network/silicoin-blockchain#18]
Version 0.04, the hard disk has been read non-stop, never stopped

**Describe the bug**
A clear and concise description of what the bug is. (If what you are experiencing is NOT a bug but instead a support issue, please open a Discussion instead!)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Linux]
- OS Version/Flavor: [e.g. CentOS 7.2]
- CPU: [e.g. Intel Xeon 8175M]

**Additional context**

**Comment by albertxuzeng** [comment]
Fixed in 0.0.9 version
