### ISSUE TITLE
[BUG]It's not fair

### ISSUE THREAD

**Issue by wc357** [silicoin-network/silicoin-blockchain#180]
When I started plot, there was no SIT, so I had to buy it. Unfortunately, I found it on Coinstore , where you can only buy and can't withdraw . So I had to plot without stake, there was no SIT at all for a month, how to start was a very big problem.There is no way to buy SIT - no SIT to stake - get 0 SIT - no SIT to stake.It feels like a dead circle.

**Comment by rabbitii** [comment]
https://trade.citex.info/trade/SIT_USDT

You can buy there and transfer to your wallet.

**Comment by albertcoady** [comment]
You can find our discord channel in website: https://www.sitnetwork.org. You can get more help in our community.
