### ISSUE TITLE
> Same here...

### ISSUE THREAD

**Issue by LordRayden2020** [silicoin-network/silicoin-blockchain#181]
> Same here...
> Stuck on 195,106 for 5 days.
> Fresh install with1.1.5 (I thought maybe something is wrong in the config so I deleted everything and started from scratch).
> Downloaded a new DB file which is also stuck on 195,106...

Please tell me your OS platform.

_Originally posted by @albertcoady in https://github.com/silicoin-network/silicoin-blockchain/issues/178#issuecomment-999307912_

SIT is running on a Windows 10 Pro 21H2 (Build: 19044.1415)
My Plots are on an Ubuntu Machine with Samba 4 and on a Windows 10 Pro Machine.
All the drives are connected over the network to the machine running SIT and all of them are mapped to local driver letters. The whole setup worked without Problems until the 17.12.2021, that’s when it all got stuck.

**Comment by LordRayden2020** [comment]
Sorry, to late I noticed that the other thread was about wallet not syncing. I am talking about the node not syncing.

**Comment by LordRayden2020** [comment]
Interesting...
In the last five days I tried “.\sit.exe start node -r” for at least hundred times and it never worked. Today it starts “hiccups”. After issuing the command the node starts syncing, but only for a few minutes, then it stops again, I have to issue the command again to again get it to work for a few minutes. But at least I am at 207,303 already, still this cant be the solution, how could I farm anything if I have to restart the node every few minutes.

**Comment by albertcoady** [comment]
Is your Silicoin app version 1.1.5 or higher?

**Comment by LordRayden2020** [comment]
1.1.5(Venus)

**Comment by albertcoady** [comment]
You need to restart wallet service as well. After restart, you should wait for some time (I think maybe one hour) to let the wallet resume syncing.
