### ISSUE TITLE
[BUG] Wallet and farm are not in sync (UBUNTU)

### ISSUE THREAD

**Issue by maxkrukov** [silicoin-network/silicoin-blockchain#185]
Does somebody have the same problem?
```
(venv) mkriukov@mining-rig2:~/silicoin$ sit wallet show
Wallet height: 224623
Sync status: Not synced
Balances, fingerprint: 759994173
Wallet ID 1 type STANDARD_WALLET Chia Wallet
   -Total Balance: 1.25 sit (1250000000000 mojo)
   -Pending Total Balance: 1.25 sit (1250000000000 mojo)
   -Spendable: 1.25 sit (1250000000000 mojo)
(venv) mkriukov@mining-rig2:~/silicoin$ sit version
Venus 1.2.0_dev(Venus)
(venv) mkriukov@mining-rig2:~/silicoin$ 
(venv) mkriukov@mining-rig2:~/silicoin$ sit farm summary
Farming status: Not synced or not connected to peers
```

**Comment by buglantiss** [comment]
confirmed

**Comment by albertcoady** [comment]
Have you guys tried to restart the full node and wallet service?

**Comment by qianggefcnb** [comment]
This is not an individual problem. My friends and I have the same problem. Our version is 1.2
Now we have to go back to 1.1 5 version, and delete the synchronization data and resynchronize
This wastes us at least 2 days. It's really not easy to say I love you

**Comment by maxkrukov** [comment]
> Have you guys tried to restart the full node and wallet service?

Yes, I restarted systemd unit and rebooted node. Other forks are working well

**Comment by zak371** [comment]
I have the same issue with Ubuntu - version 1.2.0 not running. No issues with other forks. Version 1.1.5 is working  o.k.

**Comment by Industrial-Content-Studios** [comment]
same issue on w10, no more sync, no matter what I do

**Comment by Einheit-101** [comment]
Now my sync stopped at height 297.452, 01/09/2022, 13:14:00
This needs an urgent fix
