### ISSUE TITLE
[BUG]Error get staking for public key xxxxxxx

### ISSUE THREAD

**Issue by zhouj889** [silicoin-network/silicoin-blockchain#187]
```bash
2022-01-04T10:56:28.561 harvester chia.harvester.harvester: ERROR    Error get staking for public key 92bb9288a38347583231a580dfbcc610c9b388bd1f3d94199b512ba48be76610fea460facdb8940b5e19d9b0121373ac, b'\x92\xbb\x92\x88\xa3\x83GX21\xa5\x80\xdf\xbc\xc6\x10\xc9\xb3\x88\xbd\x1f=\x94\x19\x9bQ+\xa4\x8b\xe7f\x10\xfe\xa4`\xfa\xcd\xb8\x94\x0b^\x19\xd9\xb0\x12\x13s\xac'
```
i install sit by follow the instruction and everything is right,my harvester client is ploting normal,but when i check the wallet host ,i find it get a worry staking address ,and my harvester client show this error above 

how do i solve this problem ?

**Comment by albertcoady** [comment]
How did you check your wallet host? Did you run any command to check?

**Comment by zhouj889** [comment]
> How did you check your wallet host? Did you run any command to check?

yes,i link one of my harvester and do `sit farm summary` then i find the staking address is worry(balance is a worry number),so i get the first wallet address and go a exprlor website to surely that my wallet address is right , my harverster is going eligible right now , this also mean that my 24 word and wallet addresss is right,my staking adress balance  is a difference of more than 5,000 coin to the worry address.
now im going to install aging,hope it work
