### ISSUE TITLE
[BUG] The number of proofs is searched a lot, but the winning rate is not the same. It just keeps the hard disk reading and writing. Please improve the efficiency.

### ISSUE THREAD

**Issue by Nok74** [silicoin-network/silicoin-blockchain#19]
The number of proofs is searched a lot, but the winning rate is not the same. It just keeps the hard disk reading and writing. Please improve the efficiency.
![7E8C8450-E5FB-47A2-8EFA-CB4E570A604B](https://user-images.githubusercontent.com/86510052/124115980-04336900-daa1-11eb-87f7-380408a438b5.jpeg)
![Uploading 86F6FB91-79A8-4D85-85C0-5DFC0F0B5401.jpeg…]()

**Describe the bug**
A clear and concise description of what the bug is. (If what you are experiencing is NOT a bug but instead a support issue, please open a Discussion instead!)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Linux]
- OS Version/Flavor: [e.g. CentOS 7.2]
- CPU: [e.g. Intel Xeon 8175M]

**Additional context**

**Comment by feliperiosm** [comment]
Hello, I´m having the same problem... with 1400+ plots getting 50+ passed filter so the drives are crazy and they cant process below 5 seconds reaching 20 and 30 seconds... went down to 650 plots but still getting 16 - 23 passed filter. BTW no rewards.

OS: Big sur
CPU: I7 Quad Core

**Comment by alex8900vbs** [comment]
its normal this read disk rate????

**Comment by albertxuzeng** [comment]
Fix in 0.0.9 version
