### ISSUE TITLE
[BUG]Can't withdraw all sits From Staking Address

### ISSUE THREAD

**Issue by sofregaz** [silicoin-network/silicoin-blockchain#191]
Hi, 
1、sit version: 1.2.0
2、on command line, input the command: 
`sit wallet send_from -s xxxxxx -t xxxxx `, occur the following warning:
`2022-01-11T15:01:25.550 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'INVALID_BLOCK_COST',
 'status': 3,
 'txid': '0x5fbfa1aa7b13bbb2237df100a0f8d152520b34610a87d7abff3082d115acff9b'}
2022-01-11T15:01:26.944 wallet chia.wallet.wallet_node    : WARNING  SpendBundle has been rejected by the FullNode. {'error': 'INVALID_BLOCK_COST',
 'status': 3,
 'txid': '0x5fbfa1aa7b13bbb2237df100a0f8d152520b34610a87d7abff3082d115acff9b'}
2022-01-11T15:01:27.225 wallet chia.consensus.block_header_validation: INFO     [debug] validate block 1.694634298946897077013977471
2022-01-11T15:01:27.488 full_node chia.full_node.full_node: INFO     ⏲️ Finished signage point 54/64: CC: 1cee5c63f6479acec822ec8ff72a44af55efcb25fde59f65f3223aaf6bf45e3b RC: e19c62a45dc0127fd541cf407080d4553525a0c8d76702d8d492cdb1df621e6c`

and then the sits doesn't send to the target address successfully,  the transaction status is always "pending".

how to solve this problem?

**Comment by albertcoady** [comment]
Can you provide your staking address ?

**Comment by zhouj889** [comment]
I have this problem too

**Comment by sofregaz** [comment]
> Can you provide your staking address ?

**Comment by sofregaz** [comment]
> 

sit1ep6ntmhvue9nkn7g279l964erdm049j9wr2zs47hwcprfsmvrj9qelljhd

**Comment by albertcoady** [comment]
Will fix it in the next release

**Comment by albertcoady** [comment]
@sofregaz you can try to install the dev branch. I added "amount" parameter to the "send_from" command. Since you have 3000 coins in your staking address, it may exceed the max cost of the block if you withdraw them all in one block.

**Comment by sofregaz** [comment]
> @sofregaz you can try to install the dev branch. I added "amount" parameter to the "send_from" command. Since you have 3000 coins in your staking address, it may exceed the max cost of the block if you withdraw them all in one block.

just switch to the dev version，any other place need to change？

**Comment by albertcoady** [comment]
> > @sofregaz you can try to install the dev branch. I added "amount" parameter to the "send_from" command. Since you have 3000 coins in your staking address, it may exceed the max cost of the block if you withdraw them all in one block.
> 
> just switch to the dev version，any other place need to change？

Run the send_from command should be ok, no other place need to change.
