### ISSUE TITLE
[BUG] Status Not Synced

### ISSUE THREAD

**Issue by xponzy** [silicoin-network/silicoin-blockchain#192]
- OS: Windows 10 64Bits
- CPU: Intel Core i9-10850K
- SIT Version: 1.2.0

It always stays out of sync and tries to reinstall deleting the entire directory and database and still I still have the same problem.
![Screenshot_14](https://user-images.githubusercontent.com/94275985/149156874-7ec9ae51-770a-4d05-af6e-0cc003cf2fc6.png)

**Comment by Einheit-101** [comment]
This problem started to Affect a ton of people lately, especially on 1/9/2022

**Comment by Dmitriylunohod** [comment]
Эта проблема у очень многих! Разработчики ничего не делают для исправления ситуации!

**Comment by albertcoady** [comment]
You can try to download the latest db to restore the syncing

**Comment by Einheit-101** [comment]
I downloaded the latest DB file and it worked for 6 hours, now the sync stopped again.

**Comment by Mariusp91** [comment]
thanks for the answer , how can i download the last db to try start the sync ?

**Comment by Dmitriylunohod** [comment]
Thank you, I have already downloaded it and so far everything is working



Отправлено из мобильной Почты Mail.ru


пятница, 14 января 2022 г., 13:09 +0300 от ***@***.***  ***@***.***>:
