### ISSUE TITLE
[BUG] cannot connect host. Unable to sync

### ISSUE THREAD

**Issue by ariegrossman** [silicoin-network/silicoin-blockchain#194]
after installing v1.2.0, unable to connect to hosts and sync. farmer is suck on the last block. debug log shows the same errors over and over again:

2022-01-12T21:57:11.981 farmer chia.farmer.farmer         : INFO     [debug] clear cache
2022-01-12T21:57:12.862 full_node full_node_server        : INFO     Cannot connect to host 2804:431:c7e1:8c9d:982b:d6d4:177f:e8e6:22222 ssl:<ssl.SSLContext object at 0x7f0852b549c0> [Network is unreachable]

**Comment by albertcoady** [comment]
https://github.com/silicoin-network/silicoin-blockchain/wiki/Troubles-in-connecting-to-Silicoin-full-node-peers

**Comment by ariegrossman** [comment]
I've got port forwarding turned on for port 22222, and I still see this error on two different ubuntu servers on different networks. So , not a port forwarding problem.

**Comment by albertcoady** [comment]
You can use the latest db snapshot to restore

**Comment by Mariusp91** [comment]
where can i download the last db ? 
Have someone some full nodes to connect ?

**Comment by albertcoady** [comment]
You can join our discord, there is a channel to post the latest db.
