### ISSUE TITLE
[BUG] Silicoin blockchain is not syncing. 

### ISSUE THREAD

**Issue by gdiloyan** [silicoin-network/silicoin-blockchain#195]
Running 1.2.0 version on windows on 3 computers. It at least once a week is getting stuck on syncing. Nothing helps to get it continuing syncing, the only way I can do it is to delete mainnet folder and get it syncing all the way from the beginning. Very frustrating.

**Comment by albertcoady** [comment]
You can use the latest db snapshot to restore.

**Comment by gdiloyan** [comment]
Hi, thank you, can you please elaborate. I do not understand what you have wrote.
Thank you

**Comment by albertcoady** [comment]
You can join our discord, there is a channel for db
