### ISSUE TITLE
Wallet is not restoring, giving error - Exception from 'wallet' 'utf-8'

### ISSUE THREAD

**Issue by cryptosarang** [silicoin-network/silicoin-blockchain#196]
Please help else ill loose almost 150 SIT, i updated it to the latest version and then this started happening, last time also when i updated, i lost 40 SITs

Below are the details

(venv) XXX:~/silicoin$ sit farm summary
Farming status: Not synced or not connected to peers
Total silicoin farmed: 0.0
User transaction fees: 0.0
Block rewards: 0.0
Last height farmed: 0
Local Harvester
   0 plots of size: 0.000 MiB
Plot count for all harvesters: 0
Total size of plots: 0.000 MiB
Staking addresses:
Estimated network space: 45.824 PiB
Expected time to win: Never (no plots)
Note: log into your key using 'sit wallet show' to see rewards for each key
(venv) XXX:~/silicoin$ sit wallet show
No online backup file found,
 Press S to skip restore from backup
 Press F to use your own backup file: F
Please provide the full path to your backup file: /home/mani/.silicoin/mainnet/wallet/db/blockchain_wallet_v1_testnet_395011195.sqlite
Exception from 'wallet' 'utf-8'

**Comment by albertcoady** [comment]
Have you tried to restore your wallet from height 0?

**Comment by cryptosarang** [comment]
i am not sure, i updated silicoin with the bash curl command and this happened, please let me know how can i check the height of the wallet.

**Comment by albertcoady** [comment]
You can use "S" to skip restore from backup and re-sync your wallet from height 0.

**Comment by cryptosarang** [comment]
I skipped and let it sync, it Synced for a while and got  coins in wallet and not its not  syncing. where is my 150 sits which i farmed?

![1](https://user-images.githubusercontent.com/86925633/151705940-44d89b43-a954-494c-b4fd-747a5014b694.png)
