### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by rvartanov** [silicoin-network/silicoin-blockchain#2]
**Describe the bug**
A clear and concise description of what the bug is. (If what you are experiencing is NOT a bug but instead a support issue, please open a Discussion instead!)
Cannot bind to adress/port while running chia
**To Reproduce**
start the GUI
OSError: [Errno 98] error while attempting to bind on address ('127.0.0.1', 9560): address already in use
OSError: [Errno 98] error while attempting to bind on address ('127.0.0.1', 9256): address already in use

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: Ubuntu 20
**Additional context**
The GUI hangs on startup after choosing a key. Keeps loading the main screen.

**Comment by albertxuzeng** [comment]
Use "sudo netstat -tulpn | grep LISTEN" command and find out which application is occupying 9560 and 9256 port.
