### ISSUE TITLE
[BUG] Multiple port conflicts

### ISSUE THREAD

**Issue by twig123** [silicoin-network/silicoin-blockchain#20]
Silicoin has multiple port conflicts with other Chia forks, causing the Silicoin client not to function on systems already running the other forks.

I'd suggest changing the used ports as follows:

FROM > TO
9444 > 10444
9448 > 10448
9447 > 10447
9559 > 10559
9555 > 10555
9556 > 10446
9449 > 10449
9560 > 10560
9445 > 10445
9000 > 10000
9256 > 10256

**Comment by Alex11reg** [comment]
How do I change these ports? More details please

**Comment by twig123** [comment]
@Alex11reg The configuration file is located in:
C:\Users\%username%\.silicoin\mainnet\config\config.yaml

However... Even though the release says it's "mainnet", it is actually running the testnet, so it's pointless to make the changes yourself as you still wouldn't be on the live blockchain. The changes need to be adopted by the project owner/devs and committed to the code, so that the coin uses the new ports by default.

**Comment by alex8900vbs** [comment]
i hope the ports changed

**Comment by nagakong** [comment]
just open a PR?

**Comment by albertxuzeng** [comment]
Will change default ports in the next release, thanks for your suggestion :)
