### ISSUE TITLE
[BUG]silicon gui senkorinize olmuyor lutfen bu hatayı düzeltinnnnnn

### ISSUE THREAD

**Issue by west-77** [silicoin-network/silicoin-blockchain#200]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop**

- OS: 
- OS Version/Flavor: 
- CPU: 

**Additional context**

**Comment by sudo-mk-sandwich** [comment]
Same here, stuck at 385.353

Log says: Invalid block from peer: {'host': '127.0.0.1', 'port': 22222} Err.INVALID_TOTAL_ITERS

**Comment by west-77** [comment]
bendede aynı yerde dondu

**Comment by sudo-mk-sandwich** [comment]
I'm in sync now.

**Comment by west-77** [comment]
benımki wallete baglanmıyor guıde nodelerde

**Comment by west-77** [comment]
1,20 hata verıyor 1,15 kullanıyorum o daha seri

**Comment by west-77** [comment]
suan 1,15 yukledım senkorınıze oldu

**Comment by west-77** [comment]
yine dondu bunların yapacagı işi ben
