### ISSUE TITLE
tahmini kazanma süresi

### ISSUE THREAD

**Issue by west-77** [silicoin-network/silicoin-blockchain#204]
Estimated winning time says 1 day It's been 3 days

**Comment by PrEzi3** [comment]
nobody ready the bugs if these are not in english. just saying...

**Comment by west-77** [comment]
> bunlar ingilizce değilse kimse böcekleri hazırlamaz. sadece söylüyorum...

tsk ederim simdi ingilizce yazıp gonderdim
