### ISSUE TITLE
[BUG] Large number of plots causes blocks found not to be returned due to high response time

### ISSUE THREAD

**Issue by FlexiMiners** [silicoin-network/silicoin-blockchain#207]
**Describe the bug**
I have in excess of 8,000 plots, and my farmer has spent days finding proofs, however none of them have made it into my wallet because of the high response times.  I have checked the system and it is not down to the hardware as other blockchains are not experiencing the same issue.

It is also apparent that the "sit farm summary" command takes a long time, but with other blockchains it does not, so this coule be related

**To Reproduce**

Have lots of plots

In the SIT logs:
`2022-02-07T05:52:10.186 harvester chia.harvester.harvester: INFO     16 plots were eligible for farming 332c58e42c... Found 1 proofs. Time: 610.84226 s. Total 8821 plots
2022-02-07T07:00:04.740 harvester chia.harvester.harvester: INFO     26 plots were eligible for farming 02e33914f6... Found 1 proofs. Time: 92.33061 s. Total 8827 plots`

Yet other blockchains like Chia are not having such long response times:
`2022-02-07T08:21:58.091 harvester chia.harvester.harvester: INFO     21 plots were eligible for farming aab9e3ad25... Found 1 proofs. Time: 0.65105 s. Total 8835 plots
2022-02-07T08:26:59.863 harvester chia.harvester.harvester: INFO     17 plots were eligible for farming 650606a25e... Found 1 proofs. Time: 1.13922 s. Total 8835 plots`

Over the past few days I have discovered many blocks which have not been credited to my wallet:
`/home/simon/.sit/mainnet/log/debug.log:2022-02-07T05:52:10.186 harvester chia.harvester.harvester: INFO     16 plots were eligible for farming 332c58e42c... Found 1 proofs. Time: 610.84226 s. Total 8821 plots
/home/simon/.sit/mainnet/log/debug.log:2022-02-07T07:00:04.740 harvester chia.harvester.harvester: INFO     26 plots were eligible for farming 02e33914f6... Found 1 proofs. Time: 92.33061 s. Total 8827 plots
/home/simon/.sit/mainnet/log/debug.log.2:2022-02-06T14:42:20.299 harvester chia.harvester.harvester: INFO     24 plots were eligible for farming 41d33941bc... Found 1 proofs. Time: 349.20523 s. Total 8733 plots
/home/simon/.sit/mainnet/log/debug.log.2:2022-02-06T20:39:12.135 harvester chia.harvester.harvester: INFO     26 plots were eligible for farming 85bf913ed6... Found 1 proofs. Time: 520.62942 s. Total 8768 plots
/home/simon/.sit/mainnet/log/debug.log.3:2022-02-06T06:08:48.970 harvester chia.harvester.harvester: INFO     22 plots were eligible for farming a58692613c... Found 1 proofs. Time: 179.69137 s. Total 8678 plots
/home/simon/.sit/mainnet/log/debug.log.3:2022-02-06T10:29:27.963 harvester chia.harvester.harvester: INFO     26 plots were eligible for farming b313167a5a... Found 1 proofs. Time: 354.60440 s. Total 8701 plots
/home/simon/.sit/mainnet/log/debug.log.3:2022-02-06T10:50:21.737 harvester chia.harvester.harvester: INFO     21 plots were eligible for farming 8ca81df035... Found 1 proofs. Time: 265.90545 s. Total 8704 plots
/home/simon/.sit/mainnet/log/debug.log.3:2022-02-06T13:21:38.273 harvester chia.harvester.harvester: INFO     18 plots were eligible for farming 6c99367de4... Found 1 proofs. Time: 89.77003 s. Total 8723 plots
/home/simon/.sit/mainnet/log/debug.log.4:2022-02-05T23:02:19.862 harvester chia.harvester.harvester: INFO     11 plots were eligible for farming 76250be896... Found 1 proofs. Time: 3.58713 s. Total 8640 plots
/home/simon/.sit/mainnet/log/debug.log.5:2022-02-05T15:36:22.401 harvester chia.harvester.harvester: INFO     18 plots were eligible for farming 30952fdd0b... Found 1 proofs. Time: 84.29794 s. Total 8596 plots
/home/simon/.sit/mainnet/log/debug.log.6:2022-02-05T12:21:46.867 harvester chia.harvester.harvester: INFO     18 plots were eligible for farming 21ce504829... Found 1 proofs. Time: 351.72225 s. Total 8577 plots
`
I also see in the logs:
`
2022-02-07T07:00:04.740 harvester chia.harvester.harvester: WARNING  Looking up qualities on /PoolplotsE004/plot-k32-2021-07-02-17-32-b31f3d831210dcfdd6eeebd19a099428057a8e0aeeebf5b8c8090d002b7fbf2d.plot took: 92.02646088600159. This should be below 5 seconds to minimize risk of losing rewards.
`

Again I do not see the same messages in other blockchains on the same system

- OS: Ubuntu
- OS Version/Flavor: 20.04 LTS
- CPU: Intel 6248R, 512GB RAM

**Comment by FlexiMiners** [comment]
As a Test, I removed 20 of my Plot disks from Silicoin only using the 'sit plots remove -d' command, so my plots are now sitting at 5576 and response time has improved, even the sit farm summary command returns much faster, so clearly this is a scalability bug

**Comment by PrEzi3** [comment]
Related to #175
