### ISSUE TITLE
Get your Sh*t together and please fix this freaking sync mess....

### ISSUE THREAD

**Issue by PrEzi3** [silicoin-network/silicoin-blockchain#208]
So it seems that by "brilliant and ingenious" development now there are 4 main problems that the devs created by themselves....
1 - obvious performance issues that are plaguing this fork since the introduction of staking mechanism. The more you have plots the bigger are the problems and they seem to increase exponentially causing problems even on modern CPUs IF enough plots are present (7-8k +). For a RaspberryPi Harvester to start choking it is enough to have 3000+.
2 port switch from 11xxx which was handled badly
3 certificate switch which again handled badly
4 restart of the fork / chain

Now besides the performance issues the 2-4 are creating the situation where 11xxx clients who overslept everything STILL try to connect to the newer clients.... but this is not the main issue. The main issue is that you have now literally THREE blockchains that run in parallel. 11xxx branch, 22xxx from before the restart and the 22xxx after the restart. 
And now you see a problem where the "new 22xxx" branch is at 441.3xx height and has a lot of problems coming through, because some "idi0ts" on the "old 22xxx" are on 446.xxx and are literally poisoning the new 22xxx branch.

Can we PLEASE FINALLY get this done and fixed ?  Issue a new certificate and PREVENT all the OLD blockchain clients from poisoning the new chain ?  Oh and fix the damn performance issues....

**Comment by dipol0** [comment]
Really ! May be u can make version with control version node and don't connect to old/incompatibility nodes.

**Comment by PrEzi3** [comment]
> Really ! May be u can make version with control version node and don't connect to old/incompatibility nodes.

I am not the one who pre-farmed  1 Million SIT (so theoretically - the money for the development should be there). 
I am not the one who ignores bugs for weeks and months and fails to address them. Need to say more?
