### ISSUE TITLE
[BUG] Remote Harvesters not Working in Version 1.2.2

### ISSUE THREAD

**Issue by Exzellenz** [silicoin-network/silicoin-blockchain#212]
**Describe the bug**
Remote Harvester not working after Upgrading Harvester and farmer to 1.2.2. 
I have a  Ubuntu 20 farmer machine  in my home and a remote Win 10  Harvester which is connected via OpenVPN.
Before the upgrade it was working fine. 
After i upgraded both Machines to the latest versions i see multiple entries like this in the logs:
`2022-02-21T13:35:52.156 farmer chia.farmer.farmer         : ERROR    Harvester '10.8.0.3/a1b758e8c058ce9cad89fae852cb2990751d3194784b97d3a767f2bf7b1ff78d' did not respond: (version mismatch or time out 90s)`
when i invoke  `sit farm summary` i get the following output:
`Last height farmed: 492585
Local Harvester
   281 plots of size: 27.811 TiB
Remote Harvester for IP: 10.8.0.3
   0 plots of size: 0.000 MiB
`
So i see the harvester connection but not the plots

i already initialized sit with the certifcates again but it did not help

**To Reproduce**

Upgrade remote Harvester and Farmer to 12.2.2 start farming.

**Expected behavior**
Log entries indicate that the Remote Harvester does not work

**Screenshots**

**Desktop**

- OS: Ubuntu 20.04 LTS

**Comment by endurance1968** [comment]
Please doublehcheck if the harvesters are really running 1.2.2
E.g. if you use something like
$path = Get-item -Path $ENV:LOCALAPPDATA\sit-blockchain\app*\resources\app.asar.unpacked\daemon\sit.exe (obviously windows but you might use similar on linux)
To identify the path to sit - be aware that the path has been changed from sit-blockchain to sit only. Adapt your startscript (in case you use one) - otherwise you will still use the old sit harvester.
I had a similar issue but now with all harvesters and fullnode on 1.2.2 the number of plots counted is correct

**Comment by Exzellenz** [comment]
> Please doublehcheck if the harvesters are really running 1.2.2 E.g. if you use something like $path = Get-item -Path $ENV:LOCALAPPDATA\sit-blockchain\app*\resources\app.asar.unpacked\daemon\sit.exe (obviously windows but you might use similar on linux) To identify the path to sit - be aware that the path has been changed from sit-blockchain to sit only. Adapt your startscript (in case you use one) - otherwise you will still use the old sit harvester. Now with all harvesters and fullnode on 1.2.2 the number of plots counted is correct and as consequence the staking factor/estimated time as well.

` Thanks for the response i did not use a startup script or enviroment variables i started the processes manually over powershell and  in the Python  virtual enviroment` 
this is the powershell output:
`.PS C:\Users\exz\AppData\Local\SIT\app-1.2.2\resources\app.asar.unpacked\daemon> .\sit.exe version
Venus 1.2.2_dev(Venus)` 
Bash Output on the farmer;
`
(venv) phil@DellServ4:~/silicoin$ sit version
Venus 1.2.2(Venus)
(venv) phil@DellServ4:~/silicoin$
`
So from this point i would say the versions are the same.

**Comment by Exzellenz** [comment]
Addition, i assume its not related to the remote Harvester, there is must be  a problem  in the Win10 Harvester. 
For testing purposes i turned that remote harvester into a fullnode / Farmer and There are also no plots indicated neither in  GUI Farming nor in CLI Farming. 
I even reverted to a 1.2.0 But also tehre the plots dont show up.

**Comment by albertcoady** [comment]
> Addition, i assume its not related to the remote Harvester, there is must be a problem in the Win10 Harvester.
> For testing purposes i turned that remote harvester into a fullnode / Farmer and There are also no plots indicated neither in GUI Farming nor in CLI Farming.
> I even reverted to a 1.2.0 But also tehre the plots dont show up.

It is quite strange since My Windows 10 machine works fine with GUI full node and farmer service. I will continue to investigate it.

**Comment by Exzellenz** [comment]
Issue can be Closed. 
 I had to delete  The Plot Folders from the Yaml File and then add then one by one again with the gui. 
After they have been farming in Fullnode Mode i could  change the farmer peer to the remote Farmer and now they showed up on invoking  si farm summary.
