### ISSUE TITLE
Mac OS DMG Versions for 1.2.0 and 1.2.2 do not open, stuck at connecting to wallet

### ISSUE THREAD

**Issue by PhillWalker** [silicoin-network/silicoin-blockchain#213]
Mac OS DMG Versions for 1.2.0 and 1.2.2 do not open, stuck at connecting to wallet.

They do not create any entries in the log files.

Roll back to 1.1.5 and it works fine.

**Comment by albertcoady** [comment]
Any error output in debug.log?

**Comment by PhillWalker** [comment]
if I delete the log file, it does not create a new one, if I erase the contents it doesn't log anything...  Even on INFO....

**Comment by albertcoady** [comment]
Try deleting ~/.sit_keys and restart the app. Before you do this, please backup all your keys first. Hope this can help.
