### ISSUE TITLE
 Wallet Status:    Not Synced (839,497)

### ISSUE THREAD

**Issue by Stalker0691** [silicoin-network/silicoin-blockchain#215]
Dear administration!
For a whole month, the SILICOIN miner has not been synchronized with the network, what to do, please tell me. (Not Synced (839,497))
Sincerely.

**Comment by Stalker0691** [comment]
The problem has not been resolved, the wallet is still not syncing with the network, please help me solve the problem, regards...
 
 
Karen Manukyan 
Technical Support
X-Art LLC
Yerevan, Armenia 0002
Office: Saryan 4/6 | Store: Saryan 4/55
Tel:  +37410446677  | Mob:  +37499530972
***@***.***  |  www.x-art.am

**Comment by m0nsieurdodo** [comment]
Same probleme here :'( ... 
Stop sync at 839,497
![image](https://user-images.githubusercontent.com/29126021/187042352-d28f9085-749d-4cb8-a16a-88553dc49490.png)


How to fix it ?
