### ISSUE TITLE
[BUG] GUI is not starting on Ubuntu 20.04

### ISSUE THREAD

**Issue by cryptosarang** [silicoin-network/silicoin-blockchain#22]
i installed Silicoin as mentioned in install from source but after activating and running silicoin, the GUI is not appearing. on CLI the below message is showing that its running

Starting daemon
chia_harvester: started
chia_farmer: started
chia_full_node: started
chia_wallet: started

Please let me know if i am missing something

**Comment by morgado198028** [comment]
i cannot even install that

**Comment by albertxuzeng** [comment]
GUI is not provided in ubuntu for the current phase.

**Comment by cryptosarang** [comment]
then how i can check how many SIT i mined?
