### ISSUE TITLE
[BUG] Port conflicts with other Chia Forks

### ISSUE THREAD

**Issue by Jared-woodruff** [silicoin-network/silicoin-blockchain#23]
Node port uses 9444, which is the same as the Spare-Network.
Recommended port for this project would be 11444.

**Comment by 8465231** [comment]
I am having the same issue, it will not launch / sync properly when running other chia based blockchains.

**Comment by Jared-woodruff** [comment]
> I am having the same issue, it will not launch / sync properly when running other chia based blockchains.

In your config file for Silicoin, change all port references to 9### to 11###.

Easiest way to do it is with a text editor like Notepad++, Replace text, Find What: "port: 9", Replace with:  "port: 11" 
(while client is closed), this will change all ports like:
9444, 9448, 9555 to 11444, 11448, 11555 etc...

Reboot the PC if windows to clear the ports.

Note: you will need to update your external NAT rule to use your defined Port 11444.

**Comment by albertxuzeng** [comment]
Will change the default ports in the next release.

**Comment by ariegrossman** [comment]
How do you update nat?
