### ISSUE TITLE
Wallet won't connect? directory issue?

### ISSUE THREAD

**Issue by PC101guy** [silicoin-network/silicoin-blockchain#24]
Wallet won't connect, just hangs after I click on it.  I read that it could be a promblem with default directory because it imports straight from chia but I can't seem to fix it.

**Comment by rones-dev** [comment]
I have the same - after launching GUI it is spinning forever trying to connect to the wallet ???

**Comment by therealflinchy** [comment]
+1, launching gui the main screen just spins forever, nothing happens in CLI either

**Comment by PC101guy** [comment]
I restarted pc, and only booted up silicon coin, and then I deleted the key that it automatically input from chia for me.   I then manually input my 24 word phrase and now its working.  No idea why this worked for me but it did.

**Comment by BianKo666niglio** [comment]
same problem. v0.0.4 when i start the gui infinite loop on screen connecting to wallet

in log file 

2021-07-05T17:06:25.041 daemon __main__                   : INFO     Starting Daemon Server
2021-07-05T17:06:25.043 daemon __main__                   : INFO     Not implemented
2021-07-05T17:06:25.151 daemon __main__                   : INFO     Waiting Daemon WebSocketServer closure

**Comment by PC101guy** [comment]
> 
> 
> same problem. v0.0.4 when i start the gui infinite loop on screen connecting to wallet
> 
> in log file
> 
> 2021-07-05T17:06:25.041 daemon **main** : INFO Starting Daemon Server
> 2021-07-05T17:06:25.043 daemon **main** : INFO Not implemented
> 2021-07-05T17:06:25.151 daemon **main** : INFO Waiting Daemon WebSocketServer closure

did you try what i stated above?

**Comment by therealflinchy** [comment]
> > same problem. v0.0.4 when i start the gui infinite loop on screen connecting to wallet
> > in log file
> > 2021-07-05T17:06:25.041 daemon **main** : INFO Starting Daemon Server
> > 2021-07-05T17:06:25.043 daemon **main** : INFO Not implemented
> > 2021-07-05T17:06:25.151 daemon **main** : INFO Waiting Daemon WebSocketServer closure
> 
> did you try what i stated above?

i did, no change.

**Comment by PC101guy** [comment]
https://www.youtube.com/watch?v=uOckTmOdgb0 this is a video I watched that fixed my spare and silicoin issues.   You have to change some of the ports in the config file for either one.

**Comment by therealflinchy** [comment]
it's doing it even worse with the latest commits, even though they apparently changed ports...

**Comment by PC101guy** [comment]
must be buggy, its working good for me, at the moment on the new version.   I deleted the folder like it said, only after copying over the db files because I don't want to take 6 hours to download all them again lol.  i will let you know if anything changes./

________________________________

**Comment by albertxuzeng** [comment]
v0.0.5 changed the default ports to avoid conflicting with spare
