### ISSUE TITLE
[BUG] Cannot use plots that have been used with HPool

### ISSUE THREAD

**Issue by TroyMiner** [silicoin-network/silicoin-blockchain#25]
**Describe the bug**
I have plots that were created with the Chia client and SWAR and they worked with HPool, but when I add the directory in the Silicoin GUI, the plots all have the status of "invalid plot"

**To Reproduce**
1. Install Silicoin
2. Add directory for existing plots
3. The plot listing shows all of the plots, but they are all listed as invalid plots

The plots have been used with HPool previously.

**Comment by primoco** [comment]
You need to stop hpool client restart silicon client and than restart hpool
