### ISSUE TITLE
[BUG] Can't run silicon and Spare at same time? same port 9444?

### ISSUE THREAD

**Issue by PC101guy** [silicoin-network/silicoin-blockchain#26]
**Describe the bug**
A clear and concise description of what the bug is. (If what you are experiencing is NOT a bug but instead a support issue, please open a Discussion instead!) if one of the programs is farming the other one will not connect due to using same ports, windows 10

**To Reproduce**
Steps to reproduce the behavior:  Open spare and let it start farming, then try to open silicon, or vis versa.

**Expected behavior**
A clear and concise description of what you expected to happen.  can't run both block-chains at same time

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Linux] windows 10 64 bit
- OS Version/Flavor: [e.g. CentOS 7.2] newest version all updates done.
- CPU: [e.g. Intel Xeon 8175M] ryzen 7 2700x

**Additional context**

**Comment by sharli91** [comment]
https://www.youtube.com/watch?v=uOckTmOdgb0 this is the solution

**Comment by PC101guy** [comment]
Jesus thanks man!!! you must have been at this coin for a bit longer then me :) just started yesterday, thanks for the tip!

**Comment by ariegrossman** [comment]
How does this work. Doesn't Silicoin look for connections on 9444? This is the same as SPARE.

**Comment by PC101guy** [comment]
> 
> 
> How does this work. Doesn't Silicoin look for connections on 9444? This is the same as SPARE.

Im not sure if it works or not, it says im connected and synced and farming, but i haven't won yet

**Comment by albertxuzeng** [comment]
Fixed in 0.0.5
