### ISSUE TITLE
[BUG]silicoin-blockchain is frantically reading hard drives, causing noise and waste of power resources!! Didn’t you hear that??? When to improve?

### ISSUE THREAD

**Issue by Nok74** [silicoin-network/silicoin-blockchain#27]
silicoin-blockchain is frantically reading hard drives, causing noise and waste of power resources!! Didn’t you hear that??? When to improve?

silicoin-blockchain is frantically reading hard drives, causing noise and waste of power resources!! Didn’t you hear that??? When to improve?

**Comment by therealflinchy** [comment]
i read something about the filter being reduced sometime soon?

it really needs to be, it's crazy loud and can hurt seek times for other forks... plus yeah it can't be good for power consumption.

**Comment by abspoel99** [comment]
difficulty from the silicoin GUI is set to low, as OP says ,
4% of my plots pass the plotfilter, should be mutch lower.

**Comment by albertxuzeng** [comment]
Fix in 0.0.9 version
