### ISSUE TITLE
Did not received my reward!

### ISSUE THREAD

**Issue by akashkatare5** [silicoin-network/silicoin-blockchain#31]
Hi,

I can see one of my plots found proof but I did not receive the reward. And it stopped, showing as Not Available (Not Farming) and stuck, so I restarted the application and it was gone!

Please refer attached image for reference:

![image](https://user-images.githubusercontent.com/62850215/124678868-0a7e7680-dee1-11eb-96ac-99af9ee635ad.png)

**Comment by PC101guy** [comment]
I had a somewhat similar issue, I had won 1 block yesterday and now its gone, fully synced and farming, its just not there anymore.   I am gonna delete the DB and let it re sync.
