### ISSUE TITLE
0.0.5 Connecting to wallet - still nothing!

### ISSUE THREAD

**Issue by rones-dev** [silicoin-network/silicoin-blockchain#32]
After installing 0.0.5 still can't connect to wallet/gui everything ??! Why ???

![005](https://user-images.githubusercontent.com/63009388/124731365-72998080-df12-11eb-827e-0d6bade36e2a.jpg)

**Comment by jacklingbn** [comment]
need to delete .silicoin folder then install 0.0.5 . but need to sync again from begining..

**Comment by rones-dev** [comment]
I removed ALL files related to Silicoin - did just clean & fresh instalment - and still nothing :(

**Comment by jacklingbn** [comment]
> I removed ALL files related to Silicoin - did just clean & fresh instalment - and still nothing :(

i just did mine , i close all gui,hpool and other fork. delete whole .silicoin folder , restart pc , install 0.0.5, and it can connect but sync from begining only .

**Comment by zetiancheung** [comment]
Because it conflicts with other multi dig client ports, 9448 spare is also 9448 port

**Comment by rones-dev** [comment]
0.0.5 has port changed:
_"We changed the default ports in this version to avoid conflicting with other Chia fork projects. If you upgrade from 0.0.4, please delete ~/.silicoin folder before you launch 0.0.5."_ So should work perfectly fine - but is not.

If this project can not be run with other forks then who will waste time just to run singe Silicoin where other forks have mainnet ?!

Silicoin devs get to work or you lose community attention and achieve nothing.

**Comment by zetiancheung** [comment]
Yes, the port is fixed,
&nbsp;


张泽添&nbsp;&nbsp;
中国 广东 深圳 | 销售经理
投资管理 | 赣州优服宝信息咨询管理有限公司




&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月7日(星期三) 晚上6:15
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [silicoin-network/silicoin-blockchain] 0.0.5 Connecting to wallet - still nothing! (#32)






0.0.5端口已更改：
“我们更改了此版本中的默认端口，以避免与其他Chia叉项目发生冲突。如果您从0.0.4升级，请在启动0.0.5之前删除~/.siloin文件夹。”所以应该工作得很好--但事实并非如此。

如果这个项目不能与其他叉子一起运行，那么谁会浪费时间来运行其他叉子有主板的SsingSilicoin呢？！

Silicoin开发者开始工作，否则你就失去了社区的注意力，什么也没做。

—
你收到这封信是因为你评论了。
直接回复这封电子邮件，在GitHub上查看，或取消订阅.
