### ISSUE TITLE
Silicoin network peers needed - Cannot sync 

### ISSUE THREAD

**Issue by rattfieldnz** [silicoin-network/silicoin-blockchain#34]
Hi everyone,

I've downloaded and installed Silicoin, and am looking for peers to sync my node... Without adding any peers, my node will not sync. The GUI mentions the network name being 'testnet8'. If this is something to do with my firewall or antivirus, please let me know  - I just assumed that Silicoin would work right after install, as Chia and other forks (Flax and ChiaRose) have done. 

My Install is on Windows 10 Home - running an AMD Ryzen 7 4800H processor with 8 cores, 2 x 16GB RAM @ 3200 MHz each (totalling 32GB), 1TB internal NVMe SSD for OS and another higher TBW one for plotting. More information about my machine is here: https://www.pbtech.co.nz/product/NBKASU506331/ASUS-TUF-Gaming-A15-FX506IU-HN331T-GTX-1660-Ti-Gam.

NOTE: I am not sure exactly how issues should be submitted format-wise. If mine doesn't adhere to any guidelines please let me know and I'll reformat it.

**Comment by eks500** [comment]
Hi, I was working fine with 0.0.4, but after upgrading to 0.0.5 don't connect to any peer as you say, takes forever to sync, I have to copy my old peer_table_node.sqlite file from 0.0.4 (luckily I did not delete it) and this way sync instantly, don't know if I can share this file here
