### ISSUE TITLE
[BUG] clean install ok but Command 'chia' not found, unable to start 

### ISSUE THREAD

**Issue by stanchiam** [silicoin-network/silicoin-blockchain#35]
**Describe the bug**
Did a git clone and sh install.sh then . ./activate
run chia start farmer give error "Command 'chia' not found"

**To Reproduce**

As above

**Expected behavior**
chia command not found

**Screenshots**

**Desktop (please complete the following information):**

- OS: ubuntu
- OS Version/Flavor: 20.04
- CPU: Intel Xeon E5-2687V3

**Comment by albertxuzeng** [comment]
Please use 'sit' or 'silicon' command.
