### ISSUE TITLE
[BUG] 0.0.4 had installLinux.sh and was working. The 0.0.5 is missing and not working correct.

### ISSUE THREAD

**Issue by thebabos** [silicoin-network/silicoin-blockchain#36]
I am running 0.0.4 on cli on Cenos 7 and working fine. I installed it before on installLinux.sh, now for 0.0.5 is missing and when I want to run sit famer start is telling me command not found.

Can you please include new installLinux.sh or fix the install.sh to work correct on Cenos 7. PLEASE :)
Thanks

**Comment by albertxuzeng** [comment]
Please update to 0.0.9
