### ISSUE TITLE
Since updating to 0.0.5 no syncing and Block just spin

### ISSUE THREAD

**Issue by zinc335** [silicoin-network/silicoin-blockchain#38]
Any suggestions...
![Capture](https://user-images.githubusercontent.com/87233479/125164548-be565f00-e18a-11eb-9fce-0138e3c18211.JPG)
Windows 10 install
Removed the .\silicoin folder before running

**Comment by sergiosurvival** [comment]
yo tengo el mismo problema

**Comment by swise4797** [comment]
same

**Comment by pascal-koehl** [comment]
same problem here. After update no more syncing on cli

**Comment by stanchiam** [comment]
no timelord is running, that is why it is not syncing

**Comment by rufus21221** [comment]
Same here with 0.0.8.. Everything was working just fine before I made the update.

**Comment by albertxuzeng** [comment]
Please update to 0.0.9
