### ISSUE TITLE
[BUG] Problems installing on Ubuntu 21.04

### ISSUE THREAD

**Issue by MrChickenBacon** [silicoin-network/silicoin-blockchain#39]
**Describe the bug**
I follow the install instructions [here](https://github.com/silicoin-network/silicoin-blockchain/wiki/Install-From-Source)
But when i run the Command: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/silicoin-network/silicoin-blockchain/main/install_scripts/installLinux.sh)"

I get the following error:
ERROR: Could not find a version that satisfies the requirement miniupnpc==2.1 (from versions: none)
ERROR: No matching distribution found for miniupnpc==2.1

**To Reproduce**

1. Go to 'https://github.com/silicoin-network/silicoin-blockchain/wiki/Install-From-Source.'
2. Follow instructions
4. See error when attempting to do the install command

**Expected behavior**

**Screenshots**
[Error pic](https://media.discordapp.net/attachments/855895980285362178/863556439565139988/image0.jpg?width=901&height=676)

**Desktop**

- OS: Linux
- OS Version/Flavor:  Ubuntu 21.04
- CPU: Intel i5-10400F

**Comment by MrChickenBacon** [comment]
Created my own .sh script and removed the line "pip install -i https://hosted.chia.net/simple/ miniupnpc==2.1 setproctitle==1.1.10" then it worked. Is that miniupnpc thingy required? Anyways, it's syncing right now and seem to be working.

**Comment by extrasolarCHIA** [comment]
lol thanks bro, you actually solved this issue hahahaha

have to still test tho
