### ISSUE TITLE
[BUG] app 0.0.7 tesnet not syncing

### ISSUE THREAD

**Issue by xludodx** [silicoin-network/silicoin-blockchain#40]
app 0.0.5 got no syncable anymore.
So, I installed the new app 0.0.7, 3 hours ago, syncing until 2653 then no sync.
Can anyone help?
Is the tesnet active already ?
Thanks
Kr

**Comment by bobyturk** [comment]
i have the same problem !! 2.653 stopped

**Comment by xludodx** [comment]
And I suppose we lost all farmed coins with testnet8 too...

**Comment by Frank1975M** [comment]
I have the same thing, stopped syncing at 2,653.

**Comment by stanchiam** [comment]
disaster, should we delete .silicoin in the first place? The blockchain_v1_testnet8.sqlite was 8xx mb, now the new blockchain_v1_testnet.sqlite is only 20 mb. Where can we download instead of waiting for the sync? Should we rename blockchain_v1_testnet8.sqlite as blockchain_v1_testnet.sqlite

**Comment by stanchiam** [comment]
i am going to rename it and see if it help the rest

**Comment by stanchiam** [comment]
i think everyone not syncing because there is no timelord

**Comment by Frank1975M** [comment]
I tried to roll back to 0.5 and still the same issue.

**Comment by Frank1975M** [comment]
Is anyone's working now?

**Comment by LoftyLaz** [comment]
Same. Deleted and reinstalled at 1:16 Zulu July 12
![Screenshot (1)](https://user-images.githubusercontent.com/87287770/125217376-7ae51900-e28e-11eb-902d-d7c2814d018e.png)

**Comment by stanchiam** [comment]
its a mess now and no one running timelord for the 0.0.7

**Comment by LoftyLaz** [comment]
my post fixed it lol...  i started a new plot and
![Screenshot (2)](https://user-images.githubusercontent.com/87287770/125217981-ed0a2d80-e28f-11eb-9587-fecdc39c0041.png)

**Comment by xludodx** [comment]
There was a slight move:
Peak Height 2,833
...

**Comment by stanchiam** [comment]
we need timelord

**Comment by stanchiam** [comment]
> There was a slight move:
> Peak Height 2,833
> ...

i started timelord and the syncing moved, however my pc is weak and it is using 100% cpu, sorry i have to stop the timelord

**Comment by pascal-koehl** [comment]
Same here. My CPU is 100%.. I can't let it run all the time.. How about everyone would run a Timelord with let's say just 2 or 4 cores/threads? Could that work?

**Comment by 1980tom** [comment]
Zero tSIT and still not synced. Looks like the start of the end for this little adventure.

**Comment by albertxuzeng** [comment]
Please update to 0.0.9
