### ISSUE TITLE
[BUG]No reewards , no sync.

### ISSUE THREAD

**Issue by Admin-Miner** [silicoin-network/silicoin-blockchain#41]
I am farming since 5 days no single reward or block until now.
What means testnet ? Using Windows 10. Other coins on chianet work i am farming i get rewards ? Please explain that to me. Is that a not working blockchain here, wich is still in testing phase ? Even no sync with new version. Dead project i think.

**Comment by xludodx** [comment]
It was working quite well on Testnet8 but they moved to Testnet, since then, no sync, no farming, no rewards...

**Comment by stanchiam** [comment]
no timelord is running, that is why it is not syncing

**Comment by conandrum** [comment]
Hi. Is this fixed? I just installed 0.0.9 and I have no NODES in my connections section. With ChainGreen I had to add some nodes manually and it started syncing.
How did you solve this problem?

**Comment by albertxuzeng** [comment]
You can add the following nodes manually, 

8.210.156.214:10444
119.29.164.26:10444
8.210.172.4:10444
13.58.18.26:10444
8.210.172.4:10444
