### ISSUE TITLE
[BUG why aren't the block rewards we've earned showing up?

### ISSUE THREAD

**Issue by scilang** [silicoin-network/silicoin-blockchain#42]
why aren't the block rewards we've earned showing up?

**Comment by 1980tom** [comment]
My rewards are gone and still having sync issues?!

**Comment by albertxuzeng** [comment]
Please provide your silicoin version and OS version

**Comment by Fran6o6** [comment]
hola! actualice la aplicación de silicoin y me desapareció la recompensa que había generado hasta el momento.. alguien sabe que paso?¡
