### ISSUE TITLE
Can't Sync with version 0.0.8 after update [BUG]

### ISSUE THREAD

**Issue by rufus21221** [silicoin-network/silicoin-blockchain#43]
I deleted the .\Silicoin folder. Installed the version normally.

But now it gets stuck while syncing, and the max Height is always 2,909, on all full nodes it is trying to connect to.

Version 0.0.5 was working fine btw.

![Sem Título](https://user-images.githubusercontent.com/87321141/125310760-c77e3200-e32a-11eb-9a1f-855f0cc45558.png)

**Comment by scilang** [comment]
Worst of all, my block rewards were the way

**Comment by sergiosurvival** [comment]
no sincroniza sorry

**Comment by Frank1975M** [comment]
keep using 0.05 works fine for now.

**Comment by rufus21221** [comment]
Can't sync 0.0.5 now as well... I think that there is a major crash with the server for everyone who tried to update.

**Comment by rufus21221** [comment]
It eventually started to sync with 0.0.5 but it was after hours and I was about to give up. But thank you for the tip, and good thing I kept that version's setup.

**Comment by Frank1975M** [comment]
I saved the old .silicoin file from 0.05 as .old before the upgrade. Then
when the new one did not work. I uninstaller the now one. And replaced the
file back.
Working fine at the moment.
Just need to wait for a more stable version.

**Comment by scilang** [comment]
everything is ok 0.05 version my rewards came back :)

**Comment by xludodx** [comment]
Seen what happened when they moved to Tesnet...
The rewards we gained until will disappear in next phase...

**Comment by albertxuzeng** [comment]
Please upgrade to 0.0.9
