### ISSUE TITLE
[BUG] Since moving to 0.0.7 then to 0.0.8 and finally to 0.0.9 things seem to be working again finally. The problem I have is the previous tSIT earned for participating in the network have gone. My wallet is synced but zero tSIT when I previously had 16.

### ISSUE THREAD

**Issue by 1980tom** [silicoin-network/silicoin-blockchain#45]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop**

- OS: 
- OS Version/Flavor: 
- CPU: 

**Additional context**

**Comment by stanchiam** [comment]
same, all previous tSIT gone

**Comment by z83166588** [comment]
because of the new testnet

**Comment by vjuagar** [comment]
I have the same problem. I had 34 tSIT, but i don’t have now.

**Comment by albertxuzeng** [comment]
We will send you tSIT, please be patient.
