### ISSUE TITLE
[BUG]Sits at loading saying connecting to wallet and spinning. 0.0.9 install after deleting the ./silicoin folder

### ISSUE THREAD

**Issue by jbragg68** [silicoin-network/silicoin-blockchain#46]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop**

- OS: 
- OS Version/Flavor: 
- CPU: 

**Additional context**

**Comment by albertxuzeng** [comment]
Please provide your OS version

**Comment by jbragg68** [comment]
Win server 2012r2

**Comment by albertxuzeng** [comment]
I can sync all blocks with Silicoin client at Windows Server 2012r2
