### ISSUE TITLE
Lost 2 tSIT & there are at least 20x less plots that passed the filter with version 0.0.9 [BUG]

### ISSUE THREAD

**Issue by rufus21221** [silicoin-network/silicoin-blockchain#48]
I think the title is more than enough to explain what I am experiencing.
![tSIT 009 Issues](https://user-images.githubusercontent.com/87321141/125525794-f2b6ba17-1ab7-420d-9f1c-c2a6d129fa93.jpg)

**Comment by jbragg68** [comment]
The tSIT will be dropped back to you soon. the plots are passing less because everyone was complaining about the drives spinning 24/7. They slowed it down to fix that problem.

**Comment by rufus21221** [comment]
No worries, I got it back! Thank you! Good work!
