### ISSUE TITLE
After updating to version 0.09 can't connect to wallet [BUG]

### ISSUE THREAD

**Issue by AlexeiKaDev** [silicoin-network/silicoin-blockchain#49]
After updating to version 0.09 can't connect to wallet [BUG]
![image](https://user-images.githubusercontent.com/45790487/125580489-1ca356ea-d4fb-4ef0-91d1-f434ee872869.png)

**Comment by albertxuzeng** [comment]
Please delete ~/.silicoin before you start 0.0.9
