### ISSUE TITLE
[BUG] Harvester did not respond / Respond came too late

### ISSUE THREAD

**Issue by jeremywhd** [silicoin-network/silicoin-blockchain#51]
**Harvester did not respond / Respond came too late**

1) Reopen the GUI

Error shows in log immediately after startup silicoin GUI.
Doesnt appear in log thereafter.

![image](https://user-images.githubusercontent.com/87419773/125599824-6d331b67-e6eb-4fd4-ba83-3aebb3378aa6.png)

Also upon restart, plots dun show automatically. It needs to be refresh to be shown

**Comment by alex8900vbs** [comment]
same problem , harvester not respond
