### ISSUE TITLE
[BUG]Still all tSIT lost from when 0.0.5 got updated. I am running the latest OS and the latest Silicoin 0.0.9 and still waiting for the promised tSIT that I had previously earned. This is not resolved until that balance is in my wallet.

### ISSUE THREAD

**Issue by 1980tom** [silicoin-network/silicoin-blockchain#54]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop**

- OS: 
- OS Version/Flavor: 
- CPU: 

**Additional context**

**Comment by KratosMining** [comment]
I updated from 0.0.5 to 0.0.9 and my tSIT gone.

Steps:
0.0.5 update to 0.0.9 - First Try:
1. closed 0.0.5 node.
2. downloaded 0.0.9 windows install file.
3. hit .exe
4. the problem with sync occured, no sycn 12 hours.

0.0.5 update to 0.0.9 - Second Try:
1. closed 0.0.5 node.
2. downloaded 0.0.9 windows install file.
3. deleted .silicoin in the user folder.
4. hit .exe
5. sync started from 0 and finally synced.
6. 2 tSIT coins I had before, have dissapeared.

Windows 10 LTSC
Xeon E5-2650V2
DDR - 16 GB

My wallet adress: 
tsit1hv48t9awxr4fc37z0jgsha5cgn8muk2aszen5akrjhlmcrtd4qysnpyapz

**Comment by KratosMining** [comment]
> I updated from 0.0.5 to 0.0.9 and my tSIT gone.
> 
> Steps:
> 0.0.5 update to 0.0.9 - First Try:
> 
> 1. closed 0.0.5 node.
> 2. downloaded 0.0.9 windows install file.
> 3. hit .exe
> 4. the problem with sync occured, no sycn 12 hours.
> 
> 0.0.5 update to 0.0.9 - Second Try:
> 
> 1. closed 0.0.5 node.
> 2. downloaded 0.0.9 windows install file.
> 3. deleted .silicoin in the user folder.
> 4. hit .exe
> 5. sync started from 0 and finally synced.
> 6. 2 tSIT coins I had before, have dissapeared.
> 
> Windows 10 LTSC
> Xeon E5-2650V2
> DDR - 16 GB
> 
> My wallet adress:
> tsit1hv48t9awxr4fc37z0jgsha5cgn8muk2aszen5akrjhlmcrtd4qysnpyapz

Thank you very much, I got my farmed coins back! Thanks Silicoin Team for your help!

**Comment by kuzu1484** [comment]
Ich habe von 0.0.5 auf 0.0.9 aktualisiert und mein 64 tSIT ist weg.  

Meine Wallet-Adresse:
tsit1l0qmkdzh5mf2pqw0adknr5lm502td9jk3zprkltcvusskqqutt0svu0u4v

**Comment by kuzu1484** [comment]
ordner ist im papiekorb.was muss ich machen damit ich mein 64 tSIT ZURUCK BEKOMME

**Comment by kuzu1484** [comment]
> ordner ist im papiekorb.was muss ich machen damit ich mein 64 tSIT ZURUCK BEKOMME

Meine Wallet-Adresse:           tsit1l0qmkdzh5mf2pqw0adknr5lm502td9jk3zprkltcvusskqqutt0svu0u4v
