### ISSUE TITLE
Can't synced on 0.0.9[BUG]

### ISSUE THREAD

**Issue by DeonLee85** [silicoin-network/silicoin-blockchain#55]
Can't synced
While synced runner good on 0.0.5
But upgrade to 0.0.9 1 day trying can't sync

**Comment by wswzgit** [comment]
same problem

**Comment by albertxuzeng** [comment]
Did you delete your ~/.silicoin folder before you upgrade to 0.0.9?

**Comment by DeonLee85** [comment]
Yes

**Comment by DeonLee85** [comment]
![Uploading IMG_20210715_132454.jpg…]()

**Comment by Finaldips** [comment]
Same issue. It was working on Tuesday, farmed one tSIT and then stopped thereafter. Thanks.

**Comment by alaska4life** [comment]
Same issue.  farmed 8 tSIT on 0.0.5, now 0.0.9 won't sync

**Comment by Fishface247** [comment]
im having the same problem wont even connect to wallet just keeps spinning. had 18 tsit on version 0,0,4

**Comment by ljboy1979** [comment]
Same as me.
![image](https://user-images.githubusercontent.com/39668313/127652995-ff55ff25-3408-468f-a122-d7ebd8d58721.png)

**Comment by Finaldips** [comment]
I managed to get it working again. I copied my old .sili folder which is in C:\Users\(YourID)\.sili to my desktop, deleted the .sili folder located in C:\Users\(YourID)\.sili then started the silicoin software up. Wait for it to sync and once it did I copied just my wallet folder over and it works :).
