### ISSUE TITLE
[BUG] Plot folders aren't loaded after restarting the GUI... also 64 tSIT gone...

### ISSUE THREAD

**Issue by SilentJinx** [silicoin-network/silicoin-blockchain#56]
The GUI (0.0.9) won't load the plot folders upon restart. Plot directories were properly added and saved into the config. Upon restarting the GUI, plot directories are NOT loaded at all (appears empty). When pressing the "Add new plot folder" the list of previously added folders shows up, however they are NOT loaded by the GUI.

Beside the above all my previous 64 tSITS are gone not showing up in 0.0.9...

Really wanted to give this project a chance and struggled with it for several days, but at this stage is so full of bugs that I've seriously considered giving up on this....

**Comment by d3athgu1s3** [comment]
Double check your config.yaml to see if the plot directory was added or not?

If added, are you running HPool? If yes, then stop HPool and run it last after you loaded everything else.

Previous tSITS will be airdropped on later date (some have started to received theirs).
