### ISSUE TITLE
updated 0.09 i lost 134 coins only give me 2.531coins[BUG]

### ISSUE THREAD

**Issue by wswzgit** [silicoin-network/silicoin-blockchain#57]
2.531 coins is a  i cannot understand number,where is my 134 coins?
![%TK($X`6QM}A _ZRXUIA R](https://user-images.githubusercontent.com/85718879/125869021-74a22fb9-e35c-4695-9d69-1bd539b7f935.png)

this is my wallets  address,please return my 134 coins
tsit16mvvslwhvfvdpkn96w9k6upqchqpg9ytw2u4xx8nl6ysplzlu97qz74uys

**Comment by xludodx** [comment]
I had the same, all coins previously farmed with tesnet8 lost.
BUt I nicely got 2.531 coins to thanks me for being naive...

**Comment by d3athgu1s3** [comment]
Silicoin is on new chain now.

Old testnet8 a.k.a testnet1 (farmed before height 96969) coin will be airdropped back to your wallet. This is the announcement from Dev in Discord. Some of the user has gotten back their previous mined coin.

"The previous tSIT has started to drop back already. It takes time and we expected the program will finish before the end of 16th Jul."

**Comment by qc-world** [comment]
I've lost around 84 coins since updating from 0.0.5 (testnet8) and still no airdrop. I hope they will appear before the end of 16th July.

**Comment by qc-world** [comment]
Do we get to keep these tokens when Mainnet will go live?

**Comment by kuzu1484** [comment]
Ich habe 0.0.9 aktualisiert und mein  64 tSIT ist weg.                                                                                          
                                                                                                  
  meine wallet adresse........FUR KONTROLLE                                                                                                                                                                                                                  
  tsit1l0qmkdzh5mf2pqw0adknr5lm502td9jk3zprkltcvusskqqutt0svu0u4v

**Comment by wswzgit** [comment]
coins  back,thanks everyone
