### ISSUE TITLE
I have version 0.4 and updateing to version 0.9

### ISSUE THREAD

**Issue by TonyCollins** [silicoin-network/silicoin-blockchain#58]
0.9 version would not open to like you say Idelected the .silicion folder...as if from 0.5 to version 0.9 But all my tsit Money disappered..I am trying to copy and paste the WALLET files to see if that works...Trouble is I do not think you can choose your Wallet receive address.. I want to try to FORWARD wallet funds from version 0.4 to  0.9... Very Tricky...

**Comment by albertxuzeng** [comment]
We will send you the missing tSIT
