### ISSUE TITLE
Upgraded and now all tokens are gone [BUG]

### ISSUE THREAD

**Issue by qc-world** [silicoin-network/silicoin-blockchain#59]
**Describe the bug**
Updating to 0..0.9 from 0.0.5 have lost 84 coins. No airdrops as of yet. 

**Expected behavior**
Please resolve this issues. Do we get to keep these tokens when Mainnet goes live?

My wallet in case you need to check is:

tsit1njq2fghte3lzgcn28ayuqc65uwv7ht9zjzglhsuuspe8t5fs2yes7x5rcv

**Comment by qc-world** [comment]
Still no response from the project team. Seems like a dead project in my opinion.

**Comment by kuzu1484** [comment]
Beschreiben Sie den Fehler
Beim Aktualisieren auf 0..0.9 von 0.0.5 haben 64 Münzen verloren. Noch keine Airdrops.

Erwartetes Verhalten
Bitte beheben Sie dieses Problem. Können wir diese Token behalten, wenn Mainnet live geht?

Meine Brieftasche für den Fall, dass Sie überprüfen müssen, ist:

tsit1njq2fghte3lzgcn28ayuqc65uwv7ht9zjzglhsuuspe8t5fs2yes7x5rcv

**Comment by eks500** [comment]
Same problem here, I upgraded yesterday and I lost about 46-48 coins, I had read that we will keep the tokens when mainnet starts. I still have the old folder as backup in case it helps. My wallet is:

tsit1vfwal7f7e3hehrel9n44fkldl2jwj0565fd85af9gyjxqeyv2kxqgcmetw
