### ISSUE TITLE
[BUG] Connecting to peers on different ports

### ISSUE THREAD

**Issue by Hedonay** [silicoin-network/silicoin-blockchain#6]
**Describe the bug**

<img width="675" alt="Screenshot 2021-06-29 at 08 11 21" src="https://user-images.githubusercontent.com/85678427/123746336-cae8d680-d8b1-11eb-93b4-83a7919830ba.png">

Is that OK, or? :O

**Comment by albertxuzeng** [comment]
Yes, it is OK

**Comment by Hedonay** [comment]
> Yes, it is OK

thank you! And we are currently still connected on testnet8, right? Where for now, plots are not shown...

**Comment by albertxuzeng** [comment]
You need to "ADD A PLOT" manually in "Farm" section.

**Comment by Hedonay** [comment]
> You need to "ADD A PLOT" manually in "Farm" section.

Please keep in mind this in for a lot of us not the first rodeo... I added them and I even added them by hand to config.yaml... I think someone is already checking that... and will open new bug if needed... let's keep this one closed and relevant... ;)

**Comment by albertxuzeng** [comment]
Yes, please open new bug if the problem still exist. Also, please provide the following files:

~/.silicoin/mainnet/config/config.yaml
~/.silicoin/mainnet/log/debug.log
