### ISSUE TITLE
[ОШИБКА]

### ISSUE THREAD

**Issue by Andreym321** [silicoin-network/silicoin-blockchain#60]
I updated from 0.0.5 to 0.0.9 and my tSIT gone.

Steps:
0.0.5 update to 0.0.9 - First Try:

closed 0.0.5 node.	downloaded 0.0.9 windows install file.	
0.0.5 update to 0.0.9 - Second Try:

closed 0.0.5 node.	downloaded 0.0.9 windows install file.	deleted .silicoin in the user folder.	hit .exe	sync started from 0 and finally synced.	16 tSIT coins I had before, have dissapeared.
Windows 10 
Xeon E5-2678V3
DDR - 23 GB

My wallet adress:
tsit1y8zx93m0zxqc2gdmvhphpsjltuwh2q74uckh34c96frvunn3pyyspwc303

**Comment by albertxuzeng** [comment]
We will send you the missing tSIT
