### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Andreym321** [silicoin-network/silicoin-blockchain#61]
I updated from 0.0.5 to 0.0.9 and my tSIT gone.

Steps:
0.0.5 update to 0.0.9 - First Try:

closed 0.0.5 node. downloaded 0.0.9 windows install file.
0.0.5 update to 0.0.9 - Second Try:

closed 0.0.5 node. downloaded 0.0.9 windows install file. deleted .silicoin in the user folder. hit .exe sync started from 0 and finally synced. 16 tSIT coins I had before, have dissapeared.
Windows 10
Xeon E5-2678V3
DDR - 23 GB

My wallet adress:
tsit1y8zx93m0zxqc2gdmvhphpsjltuwh2q74uckh34c96frvunn3pyyspwc303

**Comment by qc-world** [comment]
I lost 84 tokens. Good luck getting them back. Beside its still on Testnet so I don't think it matters much.

**Comment by eks500** [comment]
Same problem here, I upgraded yesterday and I lost about 46-48 coins, I had read that we will keep the tokens when mainnet starts. I still have the old folder as backup in case it helps. My wallet is:

tsit1vfwal7f7e3hehrel9n44fkldl2jwj0565fd85af9gyjxqeyv2kxqgcmetw

**Comment by vogtom** [comment]
I see most of the issues concerning lost coins have been closed. Does that mean the airdrop is completed? I am still missing my 12-14 tSIT.

**Comment by qc-world** [comment]
I received 53 coins. Still missing 31. My case was closed. I don't know if they will send the remaining ones. 😒

**Comment by eks500** [comment]
Me too, I received 22 of the 52 that I originally have, as I said I still have the old files, I have checked just to be sure and yeah:

![image](https://user-images.githubusercontent.com/47854326/126293370-6931b241-f155-4edd-8b94-0025e7a04b60.png)

I can paste all the blocks heights if needed too
