### ISSUE TITLE
[BUG] 0.0.9 on Windows: Cannot send Transactions. No message in the GUI, AssertionError in Log

### ISSUE THREAD

**Issue by grayfallstown** [silicoin-network/silicoin-blockchain#62]
**Describe the bug**
I cannot send any transactions with the Windows client.

**To Reproduce**

1. Install 0.0.9 on Windows
2. Send any Transaction
3. Notice that no success message or error appears
4. See no new Transaction in Wallet

**Expected behavior**
Windows client should be able to send transactions

**Screenshots**

**Before clicking Send:**
![Before clicking Send](https://user-images.githubusercontent.com/50076933/126044090-7d12e76f-0aa2-4749-91a8-ce0148f3e1c0.JPG)

**Directly after clicking Send:**
![Directly after clicking Send](https://user-images.githubusercontent.com/50076933/126044091-43833aa9-9b26-44aa-a469-bcf9a09879b7.JPG)

**Desktop**

- OS: Windows 10, almost fully up to date
- OS Version/Flavor: 
- CPU: ryzen 1700x

**Additional context**

```
2021-07-17T13:16:21.884 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 212, in safe_handle
  File "chia\rpc\rpc_server.py", line 203, in ws_api
  File "chia\rpc\wallet_rpc_api.py", line 693, in send_transaction
AssertionError

```

**Comment by grayfallstown** [comment]
The wallet_state_manager is None.

async def send_transaction(self, request):
[assert self.service.wallet_state_manager is not None](https://github.com/silicoin-network/silicoin-blockchain/blob/main/chia/rpc/wallet_rpc_api.py#L693)

**Comment by sergiosurvival** [comment]
las monedas que tengamos valdran cuando saquen la mainnet?sabe alguien si valdran saludos

**Comment by albertxuzeng** [comment]
Is it ok to set "Fee" to 0?

**Comment by grayfallstown** [comment]
WIll this be addressed?
