### ISSUE TITLE
[BUG]update0.0.9 update not working just getting spinning connection screen

### ISSUE THREAD

**Issue by Fishface247** [silicoin-network/silicoin-blockchain#63]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop**

- OS: 
- OS Version/Flavor: 
- CPU: 

**Additional context**

**Comment by Fishface247** [comment]
![image](https://user-images.githubusercontent.com/86195365/126048139-a6240ac1-bb21-48d2-98b8-db1c4d2902f4.png)

**Comment by Fishface247** [comment]
this is what im getting any help would be great

**Comment by albertxuzeng** [comment]
It seems that other process is using the 56401 port, restart the machine and try again.
