### ISSUE TITLE
[BUG] with new release 0.0.9, I lost my previous tSIT Block Rewards

### ISSUE THREAD

**Issue by zo8031** [silicoin-network/silicoin-blockchain#64]
Hi,

After installation of new release 0.0.9, I lost my previous tSIT Block Rewards, its not shown in my wallet, what happened?

Thanks

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop**

- OS: 
- OS Version/Flavor: 
- CPU: 

**Additional context**

**Comment by eks500** [comment]
Same problem here, I upgraded yesterday and I lost about 46-48 coins, I had read that we will keep the tokens when mainnet starts. I still have the old folder as backup in case it helps. My wallet is:

tsit1vfwal7f7e3hehrel9n44fkldl2jwj0565fd85af9gyjxqeyv2kxqgcmetw

**Comment by albertxuzeng** [comment]
We will send you the missing tSIT
