### ISSUE TITLE
Updated to 0.0.9

### ISSUE THREAD

**Issue by kdukes4654** [silicoin-network/silicoin-blockchain#66]
I just updated my version of yuur GUI yesterday and now my tokens are gone. I had 128 tokens and would like to retrieve them. I've included my wallet receive address down below.  Will wait for your response

tsit1gzn72zy00tvggkscgjtlcmnrl54l364uzah9h2352cqjpkvwg78q49ckpm

**Comment by kuzu1484** [comment]
ich warte auch auf antwort.....mann mann

**Comment by albertxuzeng** [comment]
We will send you the missing tSIT
