### ISSUE TITLE
0.0.9[BUG]

### ISSUE THREAD

**Issue by yangxyi740920** [silicoin-network/silicoin-blockchain#70]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop**

- OS: 
- OS Version/Flavor: 
- CPU: 

**Additional context**

Silcoin after upgrading to 0.0.9, had made 16 tSIT disappear, wallet synchronization is completed only 2.531 tSIT came back. The original the Receive Address have been changed into：tsit1f0lyn6y5rpkfk6qqz546dgmv9v3rylp34pe4h0j0cva7ggt9lf8s0x6m9s

**Comment by albertxuzeng** [comment]
We will send you the missing tSIT

**Comment by yangxyi740920** [comment]
> 我们将向您发送丢失的 tSIT

Just send the 5.21
I lost is about 16
