### ISSUE TITLE
Still missing 26 coins 

### ISSUE THREAD

**Issue by qc-world** [silicoin-network/silicoin-blockchain#71]
Hi

Since updating from 0.0.5 to 0.0.9. I'm still missing 26 coins. Got 58 through airdrop couple of days ago. 

My wallet is below. 

tsit1njq2fghte3lzgcn28ayuqc65uwv7ht9zjzglhsuuspe8t5fs2yes7x5rcv

**Comment by cuca80** [comment]
I have the same problem

My wallet is below

tsit16v3yn729m8swsyzayt76cq7lllef9p3flhe2248d0pfk85hv5z6qzes4tp
