### ISSUE TITLE
MIssing tSIT

### ISSUE THREAD

**Issue by aceyvr** [silicoin-network/silicoin-blockchain#72]
Hello

After upgrading from 0.0.5 to 0.0.9, I am missing about 112 tSIT. I use to have about 190.  now only showing 78.
what did i do wrong? Please help. Thanks

My wallet address is tsit1ucmlk84y0us5wsgdh398rtkf8a06qr4t8urfgy54lxgyjl6das5szwsrns

**Comment by chiamb** [comment]
I have similar problem. In my wallet there are pending balance few days.

**Comment by aceyvr** [comment]
Hello!

still no response yet and still missing the 112 tSIT
