### ISSUE TITLE
farming with NFT Plot -found block and only get .25 , where does the 1.75 goes? [BUG]

### ISSUE THREAD

**Issue by jacklingbn** [silicoin-network/silicoin-blockchain#80]

**Comment by Sovelo** [comment]
Same issue, I have won many blocks, but all of them are .25 coins.

**Comment by Forusim** [comment]
The NFT is created on the Chia blockchain, therefore all other forks do not have the NFT address to send 1.75 coins to.

**Comment by arturotrenard** [comment]
Hello, same problem for when will we have the solution

**Comment by Kipha01** [comment]
Use Flora's fd_cli to retrieve your missing 1.75, I gained back about 20 tSit using it.

**Comment by albertcoady** [comment]
Upgrade to 0.2.1 and you can claim your missing tSIT

**Comment by Sovelo** [comment]
> Upgrade to 0.2.1 and you can claim your missing tSIT

how? I tried using the curl command from install-from-source but it only installed v0.2.0, and now my timelord wont run.
