### ISSUE TITLE
[BUG] Second instance. Quitting.

### ISSUE THREAD

**Issue by arturotrenard** [silicoin-network/silicoin-blockchain#81]
**Describe the bug**

I am running the Chia UI and I am looking to raise the Silicon UI as a second instance and it recognizes it as if it were the same Chia instance and it does not lift. I am running other forks with no problems.

**To Reproduce**

![Screenshot from 2021-07-27 13-43-26](https://user-images.githubusercontent.com/65082809/127210520-1ec1c07c-aeea-40a6-96f3-098b5e6e2c64.png)

**Expected behavior**

**Screenshots**

**Desktop**

- OS: 
- OS Version/Flavor: 
- CPU: 

**Additional context**

**Comment by extrasolarCHIA** [comment]
why is this closed? the bug still exists. Why no one is answering here?
