### ISSUE TITLE
[BUG]ERROR    Harvester did not respond. You might need to update harvester to the latest version

### ISSUE THREAD

**Issue by ljboy1979** [silicoin-network/silicoin-blockchain#83]
Version 0.0.9  doesn't work。Check log, i saw this : ERROR    Harvester did not respond. You might need to update harvester to the latest version
![image](https://user-images.githubusercontent.com/39668313/127764196-18391151-3e4c-45c4-bf19-6ef0932ac10b.png)

**Comment by albertxuzeng** [comment]
You can check whether farmer can connect to harvester?

**Comment by ljboy1979** [comment]
how can I check?
