### ISSUE TITLE
pip install -i https://hosted.chia.net/simple/ miniupnpc==2.1 setproctitle==1.1.10 doesnt install on clear linux

### ISSUE THREAD

**Issue by sergixc** [silicoin-network/silicoin-blockchain#86]
Hello, please help. do I really need these packages?
trying to execute looks like this:
(venv) chia@clr-628cf864162742be97f95328af61ed0d~/silicoin $ pip install -i https://hosted.chia.net/simple/ miniupnpc==2.1 setproctitle==1.1.10
Looking in indexes: https://hosted.chia.net/simple/
ERROR: Could not find a version that satisfies the requirement miniupnpc==2.1 (from versions: none)
ERROR: No matching distribution found for miniupnpc==2.1

I have latest clear linux

**Comment by extrasolarCHIA** [comment]
I have the very same problem on a fresh Raspberry PI 4B install, Raspberry OS 64-bit, latest kernel

How can this be fixed? I tried using the installLinux.sh and this error occured. When I tried to copy the silicoin github via git and install it following the chia tutorial the gui seems to have launched standard chia lol.....help? broken on linux?

**Comment by shinary2** [comment]
they should change the install wiki for.
you should go like this:
git clone https://github.com/silicoin-network/silicoin-blockchain
cd silicoin-blockchain
sh install.sh
. ./activate
(for gui "sh install-gui.sh" "cd silicoin-blockchain-gui" "npm run electron")
silicoin init
silicoin keys add (put in your mnemonics)
you can just copy all the folders for plots from chia or other fork at config.yaml to silicoin config.yaml, plot folders and start it.
silicoin start farmer
thats it, have a nice day.

**Comment by sergixc** [comment]
> they should change the install wiki for.
> you should go like this:
> git clone https://github.com/silicoin-network/silicoin-blockchain
> cd silicoin-blockchain
> sh install.sh
> . ./activate
> (for gui "sh install-gui.sh" "cd chia-blockchain-gui" "npm run electron &")
> silicoin init
> silicoin keys add (put in your mnemonics)
> you can just copy all the folders for plots from chia or other fork at config.yaml to silicoin config.yaml, plot folders and start it.
> silicoin start farmer
> thats it, have a nice day.

the code I quote is from the install.sh so things you're saying does not help at all

**Comment by shinary2** [comment]
> the code I quote is from the install.sh so things you're saying does not help at all
why not just delete and fresh install with ma instruction? works fine for all people i have helped with.
