### ISSUE TITLE
[BUG]Version 0.04 can't get coins from farmland farming and harvesting

### ISSUE THREAD

**Issue by Nok74** [silicoin-network/silicoin-blockchain#9]
**Describe the bug**
A clear and concise description of what the bug is. (If what you are experiencing is NOT a bug but instead a support issue, please open a Discussion instead!)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Linux]
- OS Version/Flavor: [e.g. CentOS 7.2]
- CPU: [e.g. Intel Xeon 8175M]

**Additional context**

**Comment by albertxuzeng** [comment]
Your current farming size is 1T? 1P?

**Comment by Threadgodripper** [comment]
Same problem on windows

**Comment by Threadgodripper** [comment]
I have install it again and now drop rewards

**Comment by Nok74** [comment]
我的規模是100T
