### ISSUE TITLE
[BUG] Plot tab not working with 0.2.0. GUI turns all white

### ISSUE THREAD

**Issue by prodchia** [silicoin-network/silicoin-blockchain#91]
**Describe the bug**

Plot tab is not working on windows 10 build 19043. The GUI turns all white and unresponsive after I click on plot tab.

**To Reproduce**

1. Go to ' Windows App'
2. Click on 'Plot tab'

**Expected behavior**

**Screenshots**
Please see the attached. I have also attached the error that's produced in debug.log.

![screen](https://user-images.githubusercontent.com/85683931/132005552-3cff08bf-259a-4ca2-8be0-205be29ac22c.jpg)
[debug.txt](https://github.com/silicoin-network/silicoin-blockchain/files/7105839/debug.txt)

- OS: Windows
- OS Version/Flavor: Build 19043
- CPU: E5-2690V4

**Additional context**

**Comment by albertcoady** [comment]
please upgrade to 0.2.1
