### ISSUE TITLE
[BUG] 25 words instead of 24 when creating a new wallet

### ISSUE THREAD

**Issue by harambasapp** [silicoin-network/silicoin-blockchain#92]
You have the same issue as I have already reported on Chia-Network/chia-blockchain.

Chia-Network/chia-blockchain#8439

![silicoin error](https://user-images.githubusercontent.com/90500744/132955753-ee405366-8438-4ae6-b4ef-b0b262e89f5f.PNG)

**Comment by albertcoady** [comment]
Will fix it in the next version
